# -*- coding: utf-8 -*-
"""`assets/data/tr/names_tr.json` uretir: kayit ADLARININ Turkcesi.

  python tools/tr/build_names_tr.py

Metin cevirileri `<kind>_tr.json` dosyalarinda; adlar ayri, cunku ayni ad
yuzlerce kayitta geciyor (bir sinif ozelligi hem sinif sayfasinda, hem seviye
atlamada, hem karakter kagidinda) ve kayit basina tekrarlamanin anlami yok.
`assets/data/tr/creature_names_tr.json` ile ayni gerekce.

INGILIZCE BIRAKILANLAR
  * sinif adlari (Fighter, Wizard) ve alt sinif adlari (Champion, College of
    Lore, Oath of Devotion): ozel ad; cevrilmis kural metinleri de onlara
    Ingilizce atif yapiyor ("Fighter seviyen").
  * buyu ve canavar ozel adlari.
  * kalibi tutmayan buyulu esya adlari (bkz. `item_names.py`).

Esya adlari ARTIK cevriliyor: masada "Dagger" degil "Hançer" konusuluyor ve
envanterde yarisi Turkce yarisi Ingilizce bir liste okunmuyordu. Siradan
esyalarin tamami elle, buyulu esyalar kalipla; ikisi de `item_names.py`de.

Bir adin cevirisi yoksa ekranda Ingilizcesi gorunur; eksik ceviri hata degil.
"""
import gzip
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import item_names  # noqa: E402

#: Kalip uretimi disinda kalan sinif/alt sinif yetenek adlari.
CLASS_FEATURES = {
    "Ability Score Improvement": "Nitelik Puanı Artışı",
    "Abjuration Savant": "Koruma Uzmanı",
    # "... Spells" kalibina benzeyen ama alt sinif buyu listesi OLMAYAN
    # yetenekler; kalip bunlari bozardi ("Absorb Büyüleri").
    "Absorb Spells": "Büyü Emme",
    "Archfey Spells": "Archfey Büyüleri",
    "Artificer Spells": "Artificer Büyüleri",
    "Beast Spells": "Hayvan Biçiminde Büyü",
    "Celestial Spells": "Celestial Büyüleri",
    "Clockwork Spells": "Clockwork Büyüleri",
    "Draconic Spells": "Draconic Büyüleri",
    "Fiend Spells": "Fiend Büyüleri",
    "Genie Spells": "Cin Büyüleri",
    "Great Old One Spells": "Great Old One Büyüleri",
    "Psionic Spells": "Psiyonik Büyüler",
    "Psychic Spells": "Zihinsel Büyüler",
    "Sculpt Spells": "Büyü Şekillendirme",
    "Shadow Spells": "Gölge Büyüleri",
    "Share Spells": "Büyü Paylaşımı",
    "Signature Spells": "İmza Büyüleri",
    "Spellfire Spells": "Büyüateşi Büyüleri",
    "Undead Spells": "Undead Büyüleri",
    "Abjure Foes": "Düşmanları Defetme",
    "Acrobatic Movement": "Akrobatik Hareket",
    "Action Surge": "Eylem Patlaması",
    "Additional Fighting Style": "Ek Dövüş Tarzı",
    "Advanced Artifice": "İleri Düzenek",
    "Adventurer's Atlas": "Maceracı Atlası",
    "Agile Strikes": "Çevik Vuruşlar",
    "Alchemical Savant": "Simya Uzmanı",
    "Ancient Might": "Kadim Kudret",
    "Animal Speaker": "Hayvan Dili",
    "Aquatic Affinity": "Su Yatkınlığı",
    "Arcane Apotheosis": "Gizemli Yücelme",
    "Arcane Armor": "Gizemli Zırh",
    "Arcane Charge": "Gizemli Atılım",
    "Arcane Firearm": "Gizemli Ateşli Silah",
    "Arcane Jolt": "Gizemli Sarsıntı",
    "Arcane Recovery": "Gizemli Toparlanma",
    "Arcane Ward": "Gizemli Siper",
    "Archdruid": "Baş Druid",
    "Archer": "Okçu",
    "Armor Model": "Zırh Modeli",
    "Aspect of the Wilds": "Yabanın Sureti",
    "Assassin's Tools": "Suikastçı Takımı",
    "Assassinate": "Suikast",
    "Aura Expansion": "Hale Genişlemesi",
    "Aura of Alacrity": "Tezlik Halesi",
    "Aura of Courage": "Cesaret Halesi",
    "Aura of Devotion": "Bağlılık Halesi",
    "Aura of Elemental Shielding": "Elemental Kalkan Halesi",
    "Aura of Malevolence": "Kötücüllük Halesi",
    "Aura of Protection": "Koruma Halesi",
    "Aura of Warding": "Siper Halesi",
    "Avatar of Battle": "Savaşın Bedenlenmesi",
    "Avenging Angel": "İntikam Meleği",
    "Awakened Mind": "Uyanmış Zihin",
    "Bardic Damage": "Bardik Hasar",
    "Bardic Inspiration": "Bardik İlham",
    "Bastion of Law": "Düzenin Kalesi",
    "Battering Roots": "Döven Kökler",
    "Battle Magic": "Savaş Büyüsü",
    "Battle Ready": "Savaşa Hazır",
    "Beasts of Ill Omen": "Uğursuz Hayvanlar",
    "Beguiling Defenses": "Aldatıcı Savunma",
    "Beguiling Magic": "Aldatıcı Büyü",
    "Beguiling Twist": "Aldatıcı Çevirme",
    "Bend Luck": "Şansı Bükme",
    "Bestial Fury": "Hayvani Hiddet",
    "Bewitching Magic": "Büyüleyici Sihir",
    "Bladesong": "Kılıç Ezgisi",
    "Blessed Healer": "Kutsanmış Şifacı",
    "Blessed Strikes": "Kutsanmış Vuruşlar",
    "Blessing of Moonlight": "Ay Işığının Lütfu",
    "Blessing of the Trickster": "Düzenbazın Lütfu",
    "Blessings of Knowledge": "Bilginin Lütufları",
    "Bloodthirst": "Kan Susuzluğu",
    "Body and Mind": "Beden ve Zihin",
    "Bolstering Flames": "Güçlendiren Alevler",
    "Bonus Proficiencies": "Ek Yeterlilikler",
    "Branches of the Tree": "Ağacın Dalları",
    "Brutal Strike": "Vahşi Vuruş",
    "Bulwark of Force": "Kuvvet Siperi",
    "Celestial Resilience": "Semavi Dayanıklılık",
    "Chalice": "Kadeh",
    "Channel Divinity": "İlahi Kanal",
    "Channeler": "Kanal Açan",
    "Chemical Mastery": "Kimya Ustalığı",
    "Chilling Retribution": "Dondurucu Kısas",
    "Circle Forms": "Çember Biçimleri",
    "Circle of Mortality": "Ölümlülük Çemberi",
    "Clairvoyant Combatant": "Basiretli Savaşçı",
    "Cloak of Shadows": "Gölge Pelerini",
    "Clockwork Cavalcade": "Çarkların Geçidi",
    "Combat Inspiration": "Savaş İlhamı",
    "Combat Superiority": "Savaş Üstünlüğü",
    "Contact Patron": "Hamiyle Temas",
    "Controlled Chaos": "Denetimli Kaos",
    "Corona of Light": "Işık Tacı",
    "Cosmic Omen": "Kozmik Alamet",
    "Countercharm": "Karşı Ezgi",
    "Create Thrall": "Köle Yaratma",
    "Crown of Spellfire": "Büyüateşi Tacı",
    "Cunning Action": "Kurnaz Eylem",
    "Cunning Strike": "Kurnaz Vuruş",
    "Cutting Words": "Keskin Sözler",
    "Dance Virtuoso": "Dans Ustası",
    "Danger Sense": "Tehlike Sezisi",
    "Dao's Crush": "Dao'nun Ezişi",
    "Dark One's Blessing": "Karanlık Olan'ın Lütfu",
    "Dark One's Own Luck": "Karanlık Olan'ın Şansı",
    "Darkness": "Karanlık",
    "Darkvision": "Karanlık Görüşü",
    "Dazzling Footwork": "Göz Kamaştıran Ayak Oyunu",
    "Death Strike": "Ölüm Vuruşu",
    "Death's Friend": "Ölümün Dostu",
    "Defensive Tactics": "Savunma Taktikleri",
    "Deflect Attacks": "Saldırı Savuşturma",
    "Deflect Energy": "Enerji Savuşturma",
    "Deft Explorer": "Becerikli Kâşif",
    "Devious Strikes": "Sinsi Vuruşlar",
    "Disciple of Life": "Yaşamın Müridi",
    "Disciplined Survivor": "Disiplinli Hayatta Kalan",
    "Divination Savant": "Kehanet Uzmanı",
    "Divine Foreknowledge": "İlahi Önbilgi",
    "Divine Fury": "İlahi Hiddet",
    "Divine Intervention": "İlahi Müdahale",
    "Divine Order": "İlahi Görev",
    "Divine Reaper": "İlahi Orakçı",
    "Djinni's Escape": "Djinni'nin Kaçışı",
    "Draconic Resilience": "Ejderha Dayanıklılığı",
    "Dragon": "Ejderha",
    "Dragon Companion": "Ejderha Yoldaş",
    "Dragon Wings": "Ejderha Kanatları",
    "Dread Allegiance": "Dehşet Bağlılığı",
    "Dread Ambusher": "Dehşet Pusucusu",
    "Dread Incarnate": "Dehşetin Bedenlenmesi",
    "Dreadful Strikes": "Dehşetli Vuruşlar",
    "Dreadnaught": "Korkusuz",
    "Druidic": "Druid Dili",
    "Efreeti's Fury": "Efreeti'nin Hiddeti",
    "Elder Champion": "Kadim Şampiyon",
    "Eldritch Cannon": "Kadim Top",
    "Eldritch Hex": "Kadim Lanet",
    "Eldritch Invocations": "Kadim Yakarışlar",
    "Eldritch Master": "Kadim Usta",
    "Eldritch Strike": "Kadim Vuruş",
    "Elemental Affinity": "Elemental Yatkınlık",
    "Elemental Attunement": "Elemental Uyum",
    "Elemental Burst": "Elemental Patlama",
    "Elemental Epitome": "Elemental Zirve",
    "Elemental Fury": "Elemental Hiddet",
    "Elemental Rebuke": "Elemental Azar",
    "Elemental Smite": "Elemental Darbe",
    "Elusive": "Ele Avuca Sığmaz",
    "Empowered Channeling": "Güçlendirilmiş Kanal",
    "Empowered Evocation": "Güçlendirilmiş Yakarış",
    "Empowered Strikes": "Güçlendirilmiş Vuruşlar",
    "Envenom Weapons": "Silah Zehirleme",
    "Epic Boon": "Destansı Lütuf",
    "Evasion": "Sıyrılma",
    "Eventide's Splendor": "Akşamın İhtişamı",
    "Evocation Savant": "Yakarış Uzmanı",
    "Exceptional Training": "Olağanüstü Talim",
    "Experimental Elixir": "Deneysel İksir",
    "Expert Divination": "Uzman Kehanet",
    "Expertise": "Uzmanlık",
    "Explosive Cannon": "Patlayıcı Top",
    "Extra Attack": "Fazladan Saldırı",
    "Faithful Steed": "Sadık Binek",
    "Fanatical Focus": "Fanatik Odak",
    "Fast Hands": "Hızlı Eller",
    "Fast Movement": "Hızlı Hareket",
    "Favored Enemy": "Seçilmiş Düşman",
    "Feral Instinct": "Vahşi İçgüdü",
    "Feral Senses": "Vahşi Duyular",
    "Fey Reinforcements": "Peri Takviyesi",
    "Fiendish Resilience": "Şeytani Dayanıklılık",
    "Fighting Style": "Dövüş Tarzı",
    "Flash of Genius": "Dâhilik Kıvılcımı",
    "Fleet Step": "Tez Adım",
    "Flurry of Healing and Harm": "Şifa ve Zarar Yağmuru",
    "Foe Slayer": "Düşman Katili",
    "Font of Inspiration": "İlham Pınarı",
    "Font of Magic": "Büyü Pınarı",
    "Form of Dread": "Dehşet Biçimi",
    "Fortified Position": "Tahkim Edilmiş Mevzi",
    "Fortifying Soul": "Ruhu Tahkim Etme",
    "Frenzy": "Cinnet",
    "Frigid Explorer": "Buzul Kâşifi",
    "Frozen Haunt": "Donmuş Hayalet",
    "Full of Stars": "Yıldızlarla Dolu",
    "Genie's Splendor": "Cinin İhtişamı",
    "Ghost Walk": "Hayalet Yürüyüşü",
    "Glorious Defense": "Şanlı Savunma",
    "Grave Touched": "Mezar Dokunuşu",
    "Greater Divine Intervention": "Yüce İlahi Müdahale",
    "Greater Portent": "Yüce Kehanet",
    "Group Recovery": "Toplu Toparlanma",
    "Guarded Mind": "Korunaklı Zihin",
    "Guardian": "Muhafız",
    "Guided Precision": "Yönlendirilmiş İsabet",
    "Guided Strike": "Yönlendirilmiş Vuruş",
    "Hand of Harm": "Zarar Eli",
    "Hand of Healing": "Şifa Eli",
    "Hand of Ultimate Mercy": "Nihai Merhamet Eli",
    "Healing Light": "Şifa Işığı",
    "Heightened Focus": "Yükseltilmiş Odak",
    "Heroic Warrior": "Kahraman Savaşçı",
    "Holy Nimbus": "Kutsal Hale",
    "Homing Strikes": "Güdümlü Vuruşlar",
    "Honed Spellfire": "Bilenmiş Büyüateşi",
    "Hungering Might": "Açlık Kudreti",
    "Hunter's Lore": "Avcı Bilgisi",
    "Hunter's Prey": "Avcının Avı",
    "Hunter's Rime": "Avcının Kırağısı",
    "Hurl Through Hell": "Cehennemden Savurma",
    "Illusion Savant": "Yanılsama Uzmanı",
    "Illusory Reality": "Yanıltıcı Gerçeklik",
    "Illusory Self": "Yanıltıcı Benlik",
    "Implements of Mercy": "Merhamet Gereçleri",
    "Improved Armorer": "Gelişmiş Zırhçı",
    "Improved Blessed Strikes": "Gelişmiş Kutsanmış Vuruşlar",
    "Improved Brutal Strike": "Gelişmiş Vahşi Vuruş",
    "Improved Brutal Strike (Enhanced)": "Gelişmiş Vahşi Vuruş (İleri)",
    "Improved Circle Forms": "Gelişmiş Çember Biçimleri",
    "Improved Combat Superiority": "Gelişmiş Savaş Üstünlüğü",
    "Improved Critical": "Gelişmiş Kritik",
    "Improved Cunning Strike": "Gelişmiş Kurnaz Vuruş",
    "Improved Defender": "Gelişmiş Savunucu",
    "Improved Duplicity": "Gelişmiş İkiyüzlülük",
    "Improved Elemental Fury": "Gelişmiş Elemental Hiddet",
    "Improved Illusions": "Gelişmiş Yanılsamalar",
    "Improved Reanimation": "Gelişmiş Diriltme",
    "Improved Shadow Step": "Gelişmiş Gölge Adımı",
    "Improved War Magic": "Gelişmiş Savaş Büyüsü",
    "Improved Warding Flare": "Gelişmiş Siper Parıltısı",
    "Indomitable": "Boyun Eğmez",
    "Indomitable Might": "Boyun Eğmez Kudret",
    "Infiltration Expertise": "Sızma Uzmanlığı",
    "Infiltrator": "Sızıcı",
    "Ingenious Movement": "Marifetli Hareket",
    "Innate Sorcery": "Doğuştan Büyücülük",
    "Inspiring Commander": "İlham Veren Komutan",
    "Inspiring Movement": "İlham Veren Hareket",
    "Inspiring Smite": "İlham Veren Darbe",
    "Instinctive Pounce": "İçgüdüsel Atılış",
    "Intimidating Presence": "Yıldırıcı Varlık",
    "Invoke Duplicity": "İkiyüzlülüğü Çağırma",
    "Iron Mind": "Demir Zihin",
    "Jack of All Trades": "Her İşin Ehli",
    "Knightly Envoy": "Şövalye Elçi",
    "Know Your Enemy": "Düşmanını Tanı",
    "Land's Aid": "Toprağın Yardımı",
    "Lay On Hands": "Şifalı Eller",
    "Leading Evasion": "Öncü Sıyrılma",
    "Living Legend": "Yaşayan Efsane",
    "Lunar Form": "Ay Biçimi",
    "Macabre Modifications": "Ürkütücü Değişiklikler",
    "Mage Hand Legerdemain": "Mage Hand Hokkabazlığı",
    "Magic Item Adept": "Büyülü Eşya Ehli",
    "Magic Item Master": "Büyülü Eşya Ustası",
    "Magic Item Tinker": "Büyülü Eşya Tamircisi",
    "Magical Ambush": "Büyülü Pusu",
    "Magical Cunning": "Büyülü Kurnazlık",
    "Magical Discoveries": "Büyülü Keşifler",
    "Magical Secrets": "Büyülü Sırlar",
    "Maneuver Options": "Manevra Seçenekleri",
    "Manipulate Elements": "Elementleri Yönlendirme",
    "Mantle of Inspiration": "İlham Cübbesi",
    "Mantle of Majesty": "Haşmet Cübbesi",
    "Mapping Magic": "Harita Büyüsü",
    "Marid's Surge": "Marid'in Kabarışı",
    "Martial Arts": "Dövüş Sanatları",
    "Martial Training": "Savaş Talimi",
    "Memorize Spell": "Büyü Ezberleme",
    "Metamagic": "Üstbüyü",
    "Mind Magic": "Zihin Büyüsü",
    "Mindless Rage": "Akılsız Öfke",
    "Misty Escape": "Sisli Kaçış",
    "Misty Wanderer": "Sisli Gezgin",
    "Monk's Focus": "Monk Odağı",
    "Moon's Inspiration": "Ayın İlhamı",
    "Moonlight Step": "Ay Işığı Adımı",
    "Mystic Arcanum": "Mistik Arcanum",
    "Mystical Connection": "Mistik Bağ",
    "Natural Recovery": "Doğal Toparlanma",
    "Nature Speaker": "Doğa Dili",
    "Nature's Sanctuary": "Doğanın Sığınağı",
    "Nature's Veil": "Doğanın Perdesi",
    "Nature's Ward": "Doğanın Siperi",
    "Nature's Wrath": "Doğanın Gazabı",
    "Necrotic Husk": "Nekrotik Kabuk",
    "Noble Scion": "Soylu Evlat",
    "Oceanic Gift": "Okyanus Armağanı",
    "Open Hand Technique": "Açık El Tekniği",
    "Otherworldly Glamour": "Öte Dünya Cazibesi",
    "Overchannel": "Aşırı Kanal",
    "Pact Magic": "Ahit Büyüsü",
    "Paladin's Smite": "Paladin Darbesi",
    "Path to the Grave": "Mezara Giden Yol",
    "Peerless Athlete": "Eşsiz Atlet",
    "Peerless Skill": "Eşsiz Beceri",
    "Perfect Focus": "Kusursuz Odak",
    "Perfected Armor": "Kusursuzlaşmış Zırh",
    "Persistent Rage": "Kalıcı Öfke",
    "Phantasmal Creatures": "Hayali Yaratıklar",
    "Physician's Touch": "Hekim Dokunuşu",
    "Portent": "Kehanet",
    "Potent Cantrip": "Güçlü Ufak Büyü",
    "Power of Shadow": "Gölgenin Gücü",
    "Power of the Wilds": "Yabanın Gücü",
    "Precise Hunter": "İsabetli Avcı",
    "Preserve Life": "Yaşamı Koruma",
    "Primal Champion": "İlksel Şampiyon",
    "Primal Companion": "İlksel Yoldaş",
    "Primal Knowledge": "İlksel Bilgi",
    "Primal Lore": "İlksel İrfan",
    "Primal Order": "İlksel Görev",
    "Projected Ward": "Yansıtılmış Siper",
    "Protective Field": "Koruyucu Alan",
    "Psi-Bolstered Knack": "Psi Destekli Marifet",
    "Psi-Powered Leap": "Psi Güçlü Sıçrayış",
    "Psionic Power": "Psiyonik Güç",
    "Psionic Sorcery": "Psiyonik Büyücülük",
    "Psionic Strike": "Psiyonik Vuruş",
    "Psychic Blades": "Zihinsel Bıçaklar",
    "Psychic Defenses": "Zihinsel Savunma",
    "Psychic Teleportation": "Zihinsel Işınlanma",
    "Psychic Veil": "Zihinsel Perde",
    "Psychic Whispers": "Zihinsel Fısıltılar",
    "Quivering Palm": "Titreyen Avuç",
    "Radiance of the Dawn": "Şafağın Işıması",
    "Radiant Fire": "Işıyan Ateş",
    "Radiant Soul": "Işıyan Ruh",
    "Radiant Strikes": "Işıyan Vuruşlar",
    "Rage": "Öfke",
    "Rage of the Gods": "Tanrıların Öfkesi",
    "Rage of the Wilds": "Yabanın Öfkesi",
    "Rallying Surge": "Toparlanma Atılımı",
    "Reanimated Companion": "Diriltilmiş Yoldaş",
    "Reanimator's Skill Set": "Diriltici Becerileri",
    "Reckless Attack": "Pervasız Saldırı",
    "Refined Reanimation": "Arıtılmış Diriltme",
    "Relentless": "Amansız",
    "Relentless Avenger": "Amansız İntikamcı",
    "Relentless Hunter": "Amansız Avcı",
    "Relentless Rage": "Amansız Öfke",
    "Reliable Talent": "Güvenilir Yetenek",
    "Remarkable Athlete": "Kayda Değer Atlet",
    "Rend Mind": "Zihin Parçalama",
    "Replicate Magic Item": "Büyülü Eşya Kopyalama",
    "Restorative Reagents": "Onarıcı Bileşenler",
    "Restore Balance": "Dengeyi Onarma",
    "Restoring Touch": "Onarıcı Dokunuş",
    "Retaliation": "Misilleme",
    "Revelation in Flesh": "Ete Kemiğe Bürünen Vahiy",
    "Ritual Adept": "Ritüel Ehli",
    "Rot and Violence": "Çürüme ve Şiddet",
    "Roving": "Gezginlik",
    "Sacred Weapon": "Kutsal Silah",
    "Scholar": "Bilgin",
    "Sear Undead": "Ölümsüz Kavurma",
    "Searing Vengeance": "Kavurucu İntikam",
    "Second Wind": "İkinci Nefes",
    "Second-Story Work": "Cambazlık",
    "Self-Restoration": "Kendini Onarma",
    "Sentinel at Death's Door": "Ölüm Kapısındaki Nöbetçi",
    "Shadow Arts": "Gölge Sanatları",
    "Shadow Step": "Gölge Adımı",
    "Shadow Walk": "Gölge Yürüyüşü",
    "Shadowy Dodge": "Gölgeli Sakınma",
    "Shadowy Figments": "Gölgeli Hayaller",
    "Shared Resilience": "Paylaşılan Dayanıklılık",
    "Slippery Mind": "Kaygan Zihin",
    "Slow Fall": "Yavaş Düşüş",
    "Smite of Protection": "Koruma Darbesi",
    "Sneak Attack": "Sinsi Saldırı",
    "Song of Defense": "Savunma Ezgisi",
    "Song of Victory": "Zafer Ezgisi",
    "Sorcerous Restoration": "Büyücü Toparlanması",
    "Sorcery Incarnate": "Büyücülüğün Bedenlenmesi",
    "Soul Blades": "Ruh Bıçakları",
    "Soul of Artifice": "Düzenek Ruhu",
    "Soul of Vengeance": "İntikam Ruhu",
    "Spell Breaker": "Büyü Kırıcı",
    "Spell Mastery": "Büyü Ustalığı",
    "Spell Resistance": "Büyü Direnci",
    "Spell Thief": "Büyü Hırsızı",
    "Spell-Storing Item": "Büyü Saklayan Eşya",
    "Spellcasting": "Büyücülük",
    "Spellfire Burst": "Büyüateşi Patlaması",
    "Spirits from Beyond": "Öteden Gelen Ruhlar",
    "Stalker's Flurry": "Sinsi Avcı Yağmuru",
    "Star Map": "Yıldız Haritası",
    "Starry Form": "Yıldızlı Biçim",
    "Steady Aim": "Sabit Nişan",
    "Steel Defender": "Çelik Savunucu",
    "Steps of the Fey": "Peri Adımları",
    "Stormborn": "Fırtınadan Doğan",
    "Strange Modifications": "Tuhaf Değişiklikler",
    "Stride of the Elements": "Elementlerin Adımı",
    "Strike Fear": "Korku Salma",
    "Stroke of Luck": "Şans Eseri",
    "Student of War": "Savaş Öğrencisi",
    "Studied Attacks": "İncelenmiş Saldırılar",
    "Stunning Strike": "Sersemletici Vuruş",
    "Subclass feature": "Alt sınıf özelliği",
    "Superior Atlas": "Üstün Atlas",
    "Superior Critical": "Üstün Kritik",
    "Superior Defense": "Üstün Savunma",
    "Superior Dread": "Üstün Dehşet",
    "Superior Hunter's Defense": "Üstün Avcı Savunması",
    "Superior Hunter's Prey": "Üstün Avcı Avı",
    "Superior Inspiration": "Üstün İlham",
    "Supreme Healing": "Yüce Şifa",
    "Supreme Sneak": "Yüce Sinsilik",
    "Survivor": "Hayatta Kalan",
    "Tactical Master": "Taktik Ustası",
    "Tactical Mind": "Taktik Zihin",
    "Tactical Shift": "Taktik Kayış",
    "Tamed Surge": "Evcilleştirilmiş Kabarış",
    "Tandem Footwork": "Uyumlu Ayak Oyunu",
    "Team Tactics": "Takım Taktikleri",
    "Telekinetic Adept": "Telekinetik Ehli",
    "Telekinetic Master": "Telekinetik Usta",
    "Telekinetic Movement": "Telekinetik Hareket",
    "Telekinetic Thrust": "Telekinetik İtiş",
    "Telepathic Speech": "Telepatik Konuşma",
    "The Third Eye": "Üçüncü Göz",
    "Thief's Reflexes": "Hırsız Refleksleri",
    "Thieves' Cant": "Hırsız Argosu",
    "Thought Shield": "Düşünce Kalkanı",
    "Three Extra Attacks": "Üç Fazladan Saldırı",
    "Tides of Chaos": "Kaos Gelgitleri",
    "Tinker's Magic": "Tamirci Büyüsü",
    "Tireless": "Yorulmaz",
    "Tokens of the Departed": "Göçmüşlerin Nişaneleri",
    "Tools of the Trade": "Mesleğin Aletleri",
    "Training in War and Song": "Savaş ve Ezgi Talimi",
    "Trance of Order": "Düzen Transı",
    "Travel Along the Tree": "Ağaç Boyunca Yolculuk",
    "Trickster's Transposition": "Düzenbaz Yer Değiştirmesi",
    "Twinkling Constellations": "Parıldayan Takımyıldızlar",
    "Two Extra Attacks": "İki Fazladan Saldırı",
    "Ultimate Combat Superiority": "Nihai Savaş Üstünlüğü",
    "Umbral Form": "Gölgesel Biçim",
    "Umbral Sight": "Gölgesel Görüş",
    "Unarmored Defense": "Zırhsız Savunma",
    "Unarmored Movement": "Zırhsız Hareket",
    "Unbreakable Majesty": "Kırılmaz Haşmet",
    "Uncanny Dodge": "Esrarengiz Sakınma",
    "Uncanny Metabolism": "Esrarengiz Metabolizma",
    "Undying Sentinel": "Ölümsüz Nöbetçi",
    "Unfettered Mind": "Zincirsiz Zihin",
    "Use Magic Device": "Büyülü Aygıt Kullanma",
    "Versatile Trickster": "Çok Yönlü Düzenbaz",
    "Vitality of the Tree": "Ağacın Canlılığı",
    "Voice of Death": "Ölümün Sesi",
    "Vow of Enmity": "Husumet Yemini",
    "Wails from the Grave": "Mezardan Feryatlar",
    "War Bond": "Savaş Bağı",
    "War God's Blessing": "Savaş Tanrısının Lütfu",
    "War Magic": "Savaş Büyüsü",
    "War Priest": "Savaş Rahibi",
    "Warding Flare": "Siper Parıltısı",
    "Warping Implosion": "Büken Çöküş",
    "Warrior of the Gods": "Tanrıların Savaşçısı",
    "Weapon Mastery": "Silah Ustalığı",
    "Whispers of the Dead": "Ölülerin Fısıltıları",
    "Wholeness of Body": "Bedenin Bütünlüğü",
    "Wild Companion": "Yabani Yoldaş",
    "Wild Magic Surge": "Yabani Büyü Kabarışı",
    "Wild Resurgence": "Yabani Yeniden Doğuş",
    "Wild Shape": "Yabani Biçim",
    "Words of Creation": "Yaratılış Sözleri",
    "Wrath of the Sea": "Denizin Gazabı",
    "Wrath of the Wild": "Yabanın Gazabı",
    "Zealous Presence": "Gayretli Varlık",
}


#: Tur ozelliklerinin adlari. Metin `species_tr.json` icinde; baslik burada,
#: cunku ayni ad ("Darkvision", "Size") birden cok turde geciyor.
SPECIES_TRAITS = {
    "Adrenaline Rush": "Adrenalin Patlaması",
    "Bestial Instincts": "Hayvani İçgüdüler",
    "Brave": "Yürekli",
    "Breath Weapon": "Nefes Silahı",
    "Changeling Instincts": "Changeling İçgüdüleri",
    "Construct Resilience": "Yapıntı Dayanıklılığı",
    "Creature Type": "Yaratık Türü",
    "Damage Resistance": "Hasar Direnci",
    "Darkvision": "Karanlık Görüşü",
    "Draconic Ancestry": "Ejderha Soyu",
    "Draconic Flight": "Ejderha Uçuşu",
    "Drow Lineage": "Drow Soyu",
    "Dual Mind": "Çifte Zihin",
    "Dwarven Resilience": "Cüce Dayanıklılığı",
    "Dwarven Toughness": "Cüce Çetinliği",
    "Eerie Token": "Ürkütücü Nişane",
    "Elven Lineage": "Elf Soyu",
    "Escaped Death": "Ölümden Kaçmış",
    "Everlasting": "Ebedi",
    "Feral Pounce": "Vahşi Atılış",
    "Fey Ancestry": "Peri Soyu",
    "Fey Gift": "Peri Armağanı",
    "Fiendish Legacy": "Şeytani Miras",
    "Forest Gnome Lineage": "Forest Gnome Soyu",
    "Giant Ancestry": "Dev Soyu",
    "Gnomish Cunning": "Gnom Kurnazlığı",
    "Gnomish Lineage": "Gnom Soyu",
    "Halfling Nimbleness": "Buçukluk Çevikliği",
    "High Elf Lineage": "High Elf Soyu",
    "Howl": "Uluma",
    "Integrated Protection": "Bütünleşik Koruma",
    "Keen Senses": "Keskin Duyular",
    "Knowledge from a Past Life": "Geçmiş Yaşamdan Bilgi",
    "Large Form": "Büyük Biçim",
    "Lethargy Resilience": "Uyuşukluk Direnci",
    "Luck": "Şans",
    "Mental Discipline": "Zihinsel Disiplin",
    "Mind Link": "Zihin Bağı",
    "Naturally Stealthy": "Doğuştan Gizli",
    "Otherworldly Presence": "Öte Dünya Varlığı",
    "Powerful Build": "Güçlü Yapı",
    "Relentless Endurance": "Amansız Dayanma",
    "Resourceful": "Becerikli",
    "Rock Gnome Lineage": "Rock Gnome Soyu",
    "Sentry's Rest": "Nöbetçi Dinlenmesi",
    "Severed from Dreams": "Rüyalardan Kopuk",
    "Shape-Shifter": "Biçim Değiştiren",
    "Shifting": "Biçim Kayması",
    "Size": "Boyut",
    "Skill Versatility": "Beceri Çok Yönlülüğü",
    "Skillful": "Becerikli",
    "Specialized Design": "Özelleşmiş Tasarım",
    "Speed": "Hız",
    "Spider Climb": "Örümcek Tırmanışı",
    "Stonecunning": "Taş Sezgisi",
    "Strange Endurance": "Tuhaf Dayanıklılık",
    "Tireless": "Yorulmaz",
    "Trace of Undeath": "Ölümsüzlük İzi",
    "Trance": "Trans",
    "Vampiric Bite": "Vampir Isırığı",
    "Versatile": "Çok Yönlü",
    "Werewolf Instincts": "Kurt Adam İçgüdüleri",
    "Wood Elf Lineage": "Wood Elf Soyu",
}

#: Background fayda basliklari; SRD'de bes sabit baslik.
BACKGROUND_BENEFITS = {
    "Ability Scores": "Nitelik Puanları",
    "Feat": "Feat",
    "Skill Proficiencies": "Beceri Yeterlilikleri",
    "Tool Proficiency": "Alet Yeterliliği",
    "Equipment": "Teçhizat",
}

#: Feat adlari. Orgut ve hane OZEL adlari (Harper, Zhentarim, Siberys, Mark of
#: Storm'daki "Storm" degil ama "Harper") Ingilizce kaliyor; yalnizca cevresini
#: saran sozcuk cevriliyor -- "Harper Agent" -> "Harper Ajanı".
FEATS = {
    "Aberrant Anatomy": "Sapkın Anatomi",
    "Aberrant Dragonmark": "Sapkın Ejderha Nişanı",
    "Ability Score Improvement": "Nitelik Puanı Artışı",
    "Actor": "Oyuncu",
    "Alert": "Tetikte",
    "Archery": "Okçuluk",
    "Athlete": "Atlet",
    "Blessed Warrior": "Kutsanmış Savaşçı",
    "Blind Fighting": "Kör Dövüş",
    "Boon of Bloodshed": "Kan Dökme Lütfu",
    "Boon of Bountiful Health": "Bereketli Sağlık Lütfu",
    "Boon of Combat Prowess": "Savaş Maharati Lütfu",
    "Boon of Communication": "İletişim Lütfu",
    "Boon of Desperate Resilience": "Çaresiz Dayanıklılık Lütfu",
    "Boon of Dimensional Travel": "Boyutlar Arası Yolculuk Lütfu",
    "Boon of Energy Resistance": "Enerji Direnci Lütfu",
    "Boon of Exquisite Radiance": "Kusursuz Işıma Lütfu",
    "Boon of Fate": "Kader Lütfu",
    "Boon of Fluid Forms": "Akışkan Biçimler Lütfu",
    "Boon of Fortitude": "Metanet Lütfu",
    "Boon of Fortune's Favor": "Talih Lütfu",
    "Boon of Irresistible Offense": "Karşı Konulmaz Hücum Lütfu",
    "Boon of Poison Mastery": "Zehir Ustalığı Lütfu",
    "Boon of Recovery": "Toparlanma Lütfu",
    "Boon of Revelry": "Cümbüş Lütfu",
    "Boon of Siberys": "Siberys Lütfu",
    "Boon of Skill": "Beceri Lütfu",
    "Boon of Speed": "Hız Lütfu",
    "Boon of Spell Recall": "Büyü Hatırlama Lütfu",
    "Boon of Terror": "Dehşet Lütfu",
    "Boon of Truesight": "Gerçek Görüş Lütfu",
    "Boon of the Bright Sun": "Parlak Güneş Lütfu",
    "Boon of the Furious Storm": "Azgın Fırtına Lütfu",
    "Boon of the Night Spirit": "Gece Ruhu Lütfu",
    "Boon of the Soul Drinker": "Ruh İçen Lütfu",
    "Charger": "Hücumcu",
    "Chef": "Aşçı",
    "Cold Caster": "Soğuk Büyücü",
    "Crafter": "Zanaatkâr",
    "Crossbow Expert": "Arbalet Uzmanı",
    "Crusher": "Ezici",
    "Cult of the Dragon Initiate": "Cult of the Dragon Çırağı",
    "Defense": "Savunma",
    "Defensive Duelist": "Savunmacı Düellocu",
    "Dragonscarred": "Ejderha Yaralı",
    "Druidic Warrior": "Druid Savaşçısı",
    "Dual Wielder": "Çift Silah Kullanıcısı",
    "Dueling": "Düello",
    "Durable": "Sağlam",
    "Echoing Soul": "Yankılanan Ruh",
    "Elemental Adept": "Elemental Ehli",
    "Emerald Enclave Fledgling": "Emerald Enclave Acemisi",
    "Enclave Magic": "Enclave Büyüsü",
    "Fairy Trickster": "Peri Düzenbazı",
    "Fey-Touched": "Peri Dokunuşlu",
    "Gathered Whispers": "Toplanmış Fısıltılar",
    "Genie Magic": "Cin Büyüsü",
    "Grappler": "Kavrayıcı",
    "Great Weapon Fighting": "Büyük Silah Dövüşü",
    "Great Weapon Master": "Büyük Silah Ustası",
    "Greater Aberrant Mark": "Yüce Sapkın Nişan",
    "Greater Mark of Detection": "Yüce Sezgi Nişanı",
    "Greater Mark of Finding": "Yüce Buluş Nişanı",
    "Greater Mark of Handling": "Yüce Terbiye Nişanı",
    "Greater Mark of Healing": "Yüce Şifa Nişanı",
    "Greater Mark of Hospitality": "Yüce Konukseverlik Nişanı",
    "Greater Mark of Making": "Yüce Yapım Nişanı",
    "Greater Mark of Passage": "Yüce Geçiş Nişanı",
    "Greater Mark of Scribing": "Yüce Yazım Nişanı",
    "Greater Mark of Sentinel": "Yüce Nöbetçi Nişanı",
    "Greater Mark of Shadow": "Yüce Gölge Nişanı",
    "Greater Mark of Storm": "Yüce Fırtına Nişanı",
    "Greater Mark of Warding": "Yüce Siper Nişanı",
    "Harper Agent": "Harper Ajanı",
    "Harper Teamwork": "Harper Takım Çalışması",
    "Healer": "Şifacı",
    "Heavily Armored": "Ağır Zırhlı",
    "Heavy Armor Master": "Ağır Zırh Ustası",
    "Inspiring Leader": "İlham Veren Önder",
    "Interception": "Araya Girme",
    "Keen Mind": "Keskin Zihin",
    "Lightly Armored": "Hafif Zırhlı",
    "Living Shadow": "Yaşayan Gölge",
    "Lordly Resolve": "Efendice Kararlılık",
    "Lords' Alliance Agent": "Lords' Alliance Ajanı",
    "Lucky": "Şanslı",
    "Mage Slayer": "Büyücü Avcısı",
    "Magic Initiate": "Büyü Çırağı",
    "Mark of Detection": "Sezgi Nişanı",
    "Mark of Finding": "Buluş Nişanı",
    "Mark of Handling": "Terbiye Nişanı",
    "Mark of Healing": "Şifa Nişanı",
    "Mark of Hospitality": "Konukseverlik Nişanı",
    "Mark of Making": "Yapım Nişanı",
    "Mark of Passage": "Geçiş Nişanı",
    "Mark of Scribing": "Yazım Nişanı",
    "Mark of Sentinel": "Nöbetçi Nişanı",
    "Mark of Shadow": "Gölge Nişanı",
    "Mark of Storm": "Fırtına Nişanı",
    "Mark of Warding": "Siper Nişanı",
    "Martial Weapon Training": "Martial Silah Talimi",
    "Medium Armor Master": "Orta Zırh Ustası",
    "Mist Walker": "Sis Yürüyücüsü",
    "Moderately Armored": "Orta Zırhlı",
    "Mounted Combatant": "Atlı Savaşçı",
    "Musician": "Müzisyen",
    "Mythal Touched": "Mythal Dokunuşlu",
    "Observant": "Dikkatli",
    "Order's Resilience": "Tarikatın Dayanıklılığı",
    "Piercer": "Delici",
    "Poisoner": "Zehirci",
    "Polearm Master": "Kargı Ustası",
    "Potent Dragonmark": "Güçlü Ejderha Nişanı",
    "Protection": "Koruma",
    "Purple Dragon Commandant": "Purple Dragon Kumandanı",
    "Purple Dragon Rook": "Purple Dragon Çaylağı",
    "Resilient": "Dayanıklı",
    "Ritual Caster": "Ritüel Büyücüsü",
    "Savage Attacker": "Vahşi Saldırgan",
    "Second Skin": "İkinci Deri",
    "Sentinel": "Nöbetçi",
    "Shadow-Touched": "Gölge Dokunuşlu",
    "Sharp Eye": "Keskin Göz",
    "Sharpshooter": "Keskin Nişancı",
    "Shield Master": "Kalkan Ustası",
    "Skill Expert": "Beceri Uzmanı",
    "Skilled": "Becerikli",
    "Skulker": "Sinsi",
    "Slasher": "Kesici",
    "Speedy": "Hızlı",
    "Spell Sniper": "Büyü Nişancısı",
    "Spellfire Adept": "Büyüateşi Ehli",
    "Spellfire Spark": "Büyüateşi Kıvılcımı",
    "Street Justice": "Sokak Adaleti",
    "Survivor": "Hayatta Kalan",
    "Symbiotic Being": "Ortak Yaşayan Varlık",
    "Tavern Brawler": "Meyhane Kavgacısı",
    "Telekinetic": "Telekinetik",
    "Telepathic": "Telepatik",
    "Thrown Weapon Fighting": "Fırlatma Silahı Dövüşü",
    "Touch of Death": "Ölüm Dokunuşu",
    "Tough": "Çetin",
    "Two-Weapon Fighting": "Çift Silah Dövüşü",
    "Tyro of the Gauntlet": "Gauntlet Acemisi",
    "Unarmed Fighting": "Silahsız Dövüş",
    "War Caster": "Savaş Büyücüsü",
    "Watchers": "Watchers",
    "Weapon Master": "Silah Ustası",
    "Zhentarim Ruffian": "Zhentarim Kabadayısı",
    "Zhentarim Tactics": "Zhentarim Taktikleri",
}

#: Sinif secenekleri (Eldritch Invocation, Maneuver, Metamagic, Rune).
#: Kayit adlari `optionalfeatures.json.gz` icinde; tur adlari sozlukte
#: (`classOptionTypes`), cunku baslik olarak da gosteriliyorlar.
CLASS_OPTIONS = {
    # Eldritch Invocation
    "Agonizing Blast": "Azap Patlaması",
    "Armor of Shadows": "Gölge Zırhı",
    "Ascendant Step": "Yükselen Adım",
    "Devil's Sight": "Şeytan Görüşü",
    "Devouring Blade": "Yiyip Bitiren Kılıç",
    "Eldritch Mind": "Kadim Zihin",
    "Eldritch Smite": "Kadim Darbe",
    "Eldritch Spear": "Kadim Mızrak",
    "Fiendish Vigor": "Şeytani Dinçlik",
    "Gaze of Two Minds": "İki Zihnin Bakışı",
    "Gift of the Depths": "Derinliklerin Armağanı",
    "Gift of the Protectors": "Koruyucuların Armağanı",
    "Investment of the Chain Master": "Zincir Ustasının Kuşatması",
    "Lessons of the First Ones": "İlklerin Dersleri",
    "Lifedrinker": "Can İçen",
    "Mask of Many Faces": "Çok Yüzlü Maske",
    "Master of Myriad Forms": "Sayısız Biçimin Ustası",
    "Misty Visions": "Sisli Görüntüler",
    "One with Shadows": "Gölgelerle Bir",
    "Otherworldly Leap": "Öte Dünya Sıçrayışı",
    "Pact of the Blade": "Kılıç Ahdi",
    "Pact of the Chain": "Zincir Ahdi",
    "Pact of the Tome": "Kitap Ahdi",
    "Repelling Blast": "İten Patlama",
    "Thirsting Blade": "Susamış Kılıç",
    "Visions of Distant Realms": "Uzak Diyarların Görüntüleri",
    "Whispers of the Grave": "Mezarın Fısıltıları",
    "Witch Sight": "Cadı Görüşü",
    # Maneuver
    "Ambush": "Pusu",
    "Bait and Switch": "Yem ve Takas",
    "Commander's Strike": "Komutan Vuruşu",
    "Commanding Presence": "Buyurgan Varlık",
    "Disarming Attack": "Silahsızlandıran Saldırı",
    "Distracting Strike": "Dikkat Dağıtan Vuruş",
    "Evasive Footwork": "Kaçamak Ayak Oyunu",
    "Feinting Attack": "Çalımlı Saldırı",
    "Goading Attack": "Kışkırtan Saldırı",
    "Lunging Attack": "Hamleli Saldırı",
    "Maneuvering Attack": "Manevralı Saldırı",
    "Menacing Attack": "Korkutan Saldırı",
    "Parry": "Savuşturma",
    "Precision Attack": "İsabetli Saldırı",
    "Pushing Attack": "İten Saldırı",
    "Rally": "Toparlanma Çağrısı",
    "Riposte": "Karşı Hamle",
    "Sweeping Attack": "Süpüren Saldırı",
    "Tactical Assessment": "Taktik Değerlendirme",
    "Trip Attack": "Çelme Saldırısı",
    # Metamagic
    "Careful Spell": "Dikkatli Büyü",
    "Distant Spell": "Uzak Büyü",
    "Empowered Spell": "Güçlendirilmiş Büyü",
    "Extended Spell": "Uzatılmış Büyü",
    "Heightened Spell": "Yükseltilmiş Büyü",
    "Quickened Spell": "Hızlandırılmış Büyü",
    "Seeking Spell": "Arayan Büyü",
    "Subtle Spell": "Sessiz Büyü",
    "Transmuted Spell": "Dönüştürülmüş Büyü",
    "Twinned Spell": "İkizlenmiş Büyü",
    # Rune
    "Favored in House": "Hanede Gözde",
    "Recognized in House": "Hanede Tanınan",
    "Celebrated in House": "Hanede Saygın",
    "Preeminent in House": "Hanede Önde Gelen",
}


def sub_record_names(kind, section, table):
    """Bir kaydin alt kayit ADLARI ({kind}/{section}) icin ceviri haritasi."""
    bundle = json.load(
        gzip.open(f'assets/data/{kind}.json.gz', 'rt', encoding='utf-8')
    )
    out = {}
    for row in bundle:
        for entry in row.get(section) or []:
            if not isinstance(entry, dict):
                continue
            name = (entry.get('name') or '').strip()
            if name in table:
                out[name] = table[name]
    return dict(sorted(out.items()))


def feat_names():
    """Paketteki butun feat adlari icin ceviri haritasi."""
    bundle = json.load(
        gzip.open('assets/data/feats.json.gz', 'rt', encoding='utf-8')
    )
    return {
        row['name']: FEATS[row['name']]
        for row in bundle
        if row['name'] in FEATS
    }


def class_option_names():
    """Paketteki butun sinif secenegi adlari icin ceviri haritasi."""
    bundle = json.load(
        gzip.open(
            'assets/data/optionalfeatures.json.gz', 'rt', encoding='utf-8'
        )
    )
    return {
        row['name']: CLASS_OPTIONS[row['name']]
        for row in bundle
        if row['name'] in CLASS_OPTIONS
    }


def class_feature_names():
    """Paketteki butun yetenek adlari icin ceviri haritasi.

    Kalip tasiyan adlar ("Bard Spell List", "Core Monk Traits") uretiliyor:
    sinif/alt sinif adi Ingilizce kaliyor, kalibi Turkceleniyor. Kalibi
    olmayan ve [CLASS_FEATURES] icinde de bulunmayan adlar -- alt sinif ozel
    adlari -- disarida birakiliyor, ekranda Ingilizce gorunurler.
    """
    bundle = json.load(
        gzip.open('assets/data/classes.json.gz', 'rt', encoding='utf-8')
    )
    # "<Alt sinif> Spells" alt sinifin buyu listesi; ayni kalibi tasiyan gercek
    # yetenekler ("Absorb Spells", "Sculpt Spells") var, o yuzden kalip
    # yalnizca onek GERCEKTEN bir alt sinif adiysa uygulaniyor.
    subclasses = {row['name'] for row in bundle if row.get('subclass_of')}
    out = {}
    for row in bundle:
        for feature in row.get('features') or []:
            if feature.get('feature_type') not in (
                'CLASS_LEVEL_FEATURE',
                'CORE_TRAITS_TABLE',
            ):
                continue
            name = feature['name']
            if name in out:
                continue
            if name in CLASS_FEATURES:
                out[name] = CLASS_FEATURES[name]
            elif name.endswith(' Spell List'):
                out[name] = f'{name[: -len(" Spell List")]} Büyü Listesi'
            elif name.endswith(' Spells') and name[: -len(' Spells')] in subclasses:
                out[name] = f'{name[: -len(" Spells")]} Büyüleri'
            elif name.endswith(' Subclasses'):
                out[name] = f'{name[: -len(" Subclasses")]} Alt Sınıfları'
            elif name.endswith(' Subclass'):
                out[name] = f'{name[: -len(" Subclass")]} Alt Sınıfı'
            elif name.startswith('Core ') and name.endswith(' Traits'):
                middle = name[len('Core ') : -len(' Traits')]
                out[name] = f'Temel {middle} Özellikleri'
    return dict(sorted(out.items()))


def main():
    data = {
        '_comment': (
            'Kutuphane kayit adlarinin Turkcesi. Gosterim aninda uygulanir; '
            'veritabani ve kural ayristiricilari Ingilizce ada bakmaya devam '
            'eder. Sinif ve alt sinif adlari (Fighter, College of Lore) ozel '
            'ad oldugu icin cevrilmez. Uretim: tools/tr/build_names_tr.py'
        ),
        'classFeatures': class_feature_names(),
        'classOptions': class_option_names(),
        'feats': feat_names(),
        'speciesTraits': sub_record_names('species', 'traits', SPECIES_TRAITS),
        'backgroundBenefits': sub_record_names(
            'backgrounds', 'benefits', BACKGROUND_BENEFITS
        ),
        'items': item_names.item_names(),
        'magicItems': item_names.magic_item_names(),
    }
    path = 'assets/data/tr/names_tr.json'
    with open(path, 'w', encoding='utf-8', newline='\n') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write('\n')
    print(
        f'{path}: classFeatures {len(data["classFeatures"])}, '
        f'classOptions {len(data["classOptions"])}, '
        f'feats {len(data["feats"])}, '
        f'speciesTraits {len(data["speciesTraits"])}, '
        f'backgroundBenefits {len(data["backgroundBenefits"])}, '
        f'items {len(data["items"])}, '
        f'magicItems {len(data["magicItems"])} ad.'
    )


if __name__ == '__main__':
    main()
