/// Hece ve kalip tabanli isim ureteci.
///
/// Saf Dart, TAMAMEN OFFLINE: API anahtari gerektirmez, sinirsiz cesitlilik
/// uretir (heceleri/kelimeleri birlestirerek). Heceler ve kelimeler jeneriktir
/// — SRD/PHB'den kopya isim listesi DEGIL, bu yuzden icerik lisansi acisindan
/// serbest.
///
/// Uc uretim bicimi var, her kultur bunlardan BIRINE bagli:
///  * [_persons]   — kisi adlari: hece havuzu + cinsiyete gore son hece
///                   (+ istege bagli soyad/lakap).
///  * [_compounds] — yer adlari: onek+ek birlestirme ("Blackmoor").
///  * [_phrases]   — kalip adlar: "The Golden Dragon", "Gizli Fener".
library;

import 'dart:math';

/// Isim turunun ait oldugu ust grup (arayuzde sekmeler).
enum NameCategory { person, place, establishment, group, thing }

/// Uretilebilecek isim turleri.
enum NameCulture {
  // --- Kisi ---
  human,
  humanNorth,
  humanDesert,
  humanEast,
  elf,
  drow,
  dwarf,
  halfling,
  gnome,
  orc,
  goblin,
  tiefling,
  dragonborn,
  goliath,
  lizardfolk,
  tabaxi,
  celestial,
  undead,
  // --- Yer ---
  place,
  city,
  fortress,
  ruin,
  forest,
  mountain,
  water,
  island,
  region,
  // --- Isletme ---
  tavern,
  shop,
  temple,
  // --- Topluluk ---
  guild,
  nobleHouse,
  mercenary,
  cult,
  // --- Nesne / diger ---
  ship,
  magicItem,
  tome,
  festival,
  epithet,
}

/// Kisi adlarinda kullanilacak cinsiyet tercihi.
enum NameGender { any, male, female }

extension NameCultureInfo on NameCulture {
  NameCategory get category => switch (this) {
    NameCulture.human ||
    NameCulture.humanNorth ||
    NameCulture.humanDesert ||
    NameCulture.humanEast ||
    NameCulture.elf ||
    NameCulture.drow ||
    NameCulture.dwarf ||
    NameCulture.halfling ||
    NameCulture.gnome ||
    NameCulture.orc ||
    NameCulture.goblin ||
    NameCulture.tiefling ||
    NameCulture.dragonborn ||
    NameCulture.goliath ||
    NameCulture.lizardfolk ||
    NameCulture.tabaxi ||
    NameCulture.celestial ||
    NameCulture.undead => NameCategory.person,
    NameCulture.place ||
    NameCulture.city ||
    NameCulture.fortress ||
    NameCulture.ruin ||
    NameCulture.forest ||
    NameCulture.mountain ||
    NameCulture.water ||
    NameCulture.island ||
    NameCulture.region => NameCategory.place,
    NameCulture.tavern ||
    NameCulture.shop ||
    NameCulture.temple => NameCategory.establishment,
    NameCulture.guild ||
    NameCulture.nobleHouse ||
    NameCulture.mercenary ||
    NameCulture.cult => NameCategory.group,
    NameCulture.ship ||
    NameCulture.magicItem ||
    NameCulture.tome ||
    NameCulture.festival ||
    NameCulture.epithet => NameCategory.thing,
  };

  /// Kisi adi mi (cinsiyet/soyad secenekleri ve "NPC olarak kaydet" bunlara ozel).
  bool get isPerson => category == NameCategory.person;

  /// Cinsiyete gore ayri son hece havuzu var mi.
  bool get hasGender {
    final pool = _persons[this];
    return pool != null && pool.endF.isNotEmpty;
  }

  /// Soyad/lakap eklenebilir mi.
  bool get hasSurname => _persons[this]?.surB.isNotEmpty ?? false;
}

// --- Kisi havuzlari ---------------------------------------------------------

/// [endF] bos ise kultur cinsiyet ayrimi yapmaz (endM herkes icin kullanilir).
/// [surPrefix]/[surJoin] soyadi birlestirir: prefix + a + join + b.
typedef _Person = ({
  List<String> start,
  List<String> middle,
  List<String> endM,
  List<String> endF,
  List<String> surA,
  List<String> surB,
  String surPrefix,
  String surJoin,
});

_Person _p({
  required List<String> start,
  required List<String> middle,
  required List<String> endM,
  List<String> endF = const [],
  List<String> surA = const [],
  List<String> surB = const [],
  String surPrefix = '',
  String surJoin = '',
}) => (
  start: start,
  middle: middle,
  endM: endM,
  endF: endF,
  surA: surA,
  surB: surB,
  surPrefix: surPrefix,
  surJoin: surJoin,
);

final Map<NameCulture, _Person> _persons = {
  NameCulture.human: _p(
    start: [
      'Al',
      'Ber',
      'Cor',
      'Dan',
      'Ed',
      'Fen',
      'Gar',
      'Hal',
      'Ing',
      'Jor',
      'Kel',
      'Lorn',
      'Mar',
      'Nes',
      'Or',
      'Ren',
      'Sel',
      'Tor',
      'Val',
      'Wren',
      'Bran',
      'Cad',
      'Dov',
      'Emm',
      'Ger',
      'Hen',
      'Lys',
      'Rod',
    ],
    middle: [
      'a',
      'e',
      'i',
      'o',
      'ar',
      'en',
      'in',
      'or',
      'an',
      'el',
      'is',
      'ol',
    ],
    endM: [
      'ric',
      'dor',
      'mund',
      'ton',
      'vald',
      'wick',
      'us',
      'ard',
      'mar',
      'win',
      'bert',
      'gar',
      'stan',
      'red',
    ],
    endF: [
      'wyn',
      'san',
      'ia',
      'eth',
      'lin',
      'ra',
      'sa',
      'wen',
      'dra',
      'nia',
      'issa',
      'ith',
      'ana',
      'ele',
    ],
    surA: [
      'Black',
      'Ash',
      'Storm',
      'Field',
      'Old',
      'Hart',
      'Wode',
      'Fair',
      'Long',
      'Marsh',
      'Brack',
      'Wynd',
      'Hollow',
      'Crow',
    ],
    surB: [
      'wood',
      'water',
      'field',
      'moor',
      'hill',
      'ford',
      'bourne',
      'stone',
      'brook',
      'grave',
      'ridge',
      'well',
      'mere',
      'croft',
    ],
  ),
  NameCulture.humanNorth: _p(
    start: [
      'As',
      'Bjor',
      'Eir',
      'Fro',
      'Gud',
      'Hal',
      'Ing',
      'Jar',
      'Ket',
      'Leif',
      'Odd',
      'Ran',
      'Sig',
      'Skjal',
      'Thor',
      'Ulf',
      'Vig',
      'Yr',
    ],
    middle: ['va', 'ge', 'mun', 'ri', 'da', 'bjo', 'hil', 'ste'],
    endM: [
      'grim',
      'ulf',
      'arr',
      'stein',
      'björn',
      'mund',
      'gar',
      'vald',
      'nir',
      'rek',
      'son',
    ],
    endF: [
      'dis',
      'hild',
      'run',
      'veig',
      'frid',
      'gerd',
      'lin',
      'borg',
      'ny',
      'thra',
    ],
    surA: [
      'Frost',
      'Storm',
      'Ice',
      'Bear',
      'Wolf',
      'Sea',
      'Snow',
      'Rime',
      'Thunder',
      'Elk',
    ],
    surB: [
      'born',
      'fang',
      'breaker',
      'wake',
      'mane',
      'song',
      'shield',
      'howl',
      'strider',
      'sworn',
    ],
  ),
  NameCulture.humanDesert: _p(
    start: [
      'Ab',
      'Ah',
      'Bas',
      'Fa',
      'Ha',
      'Ib',
      'Ja',
      'Ka',
      'Kha',
      'Ma',
      'Na',
      'Qa',
      'Ra',
      'Sa',
      'Ta',
      'Ya',
      'Zah',
      'Nu',
    ],
    middle: ['ri', 'sa', 'di', 'ma', 'la', 'ha', 'ib', 'ra', 'ze'],
    endM: ['im', 'ir', 'ad', 'an', 'ud', 'iq', 'am', 'ez', 'ul', 'ash'],
    endF: ['a', 'ah', 'iya', 'een', 'ida', 'ara', 'ina', 'ura', 'ya'],
    surA: ['Sand', 'Sun', 'Dune', 'Salt', 'Ember', 'Mirage', 'Palm', 'Star'],
    surB: [
      'strider',
      'seeker',
      'wind',
      'born',
      'crown',
      'road',
      'well',
      'weaver',
    ],
    surPrefix: 'al-',
  ),
  NameCulture.humanEast: _p(
    start: [
      'Ai',
      'Chen',
      'Dai',
      'Hiro',
      'Jin',
      'Kae',
      'Kaz',
      'Lian',
      'Mei',
      'Nao',
      'Ren',
      'Ryu',
      'Shen',
      'Tae',
      'Wei',
      'Xio',
      'Yuki',
      'Zhen',
    ],
    middle: ['no', 'ka', 'shi', 'ri', 'to', 'yu', 'ha', 'mi'],
    endM: ['ro', 'ken', 'sho', 'take', 'zan', 'long', 'jiro', 'hito', 'gang'],
    endF: ['ko', 'mi', 'ka', 'na', 'hua', 'lin', 'yin', 'sumi', 'rei'],
    surA: [
      'Jade',
      'Iron',
      'Silent',
      'Autumn',
      'Crane',
      'Lotus',
      'Cloud',
      'Bamboo',
    ],
    surB: [
      'River',
      'Mountain',
      'Blossom',
      'Path',
      'Gate',
      'Moon',
      'Wind',
      'Blade',
    ],
    surJoin: ' ',
  ),
  NameCulture.elf: _p(
    start: [
      'Ae',
      'Cae',
      'El',
      'Fae',
      'Gal',
      'Il',
      'Lae',
      'My',
      'Ny',
      'Ri',
      'Sy',
      'Tha',
      'Va',
      'Yl',
      'Zeh',
      'Ael',
      'Ith',
      'Lo',
      'Que',
      'Sha',
    ],
    middle: [
      'la',
      'ri',
      'the',
      'nu',
      'ma',
      'lu',
      'si',
      'va',
      'ni',
      'ae',
      'lo',
      'thi',
    ],
    endM: [
      'dir',
      'nor',
      'thil',
      'las',
      'mir',
      'ion',
      'reth',
      'dan',
      'thar',
      'wyr',
      'ael',
    ],
    endF: [
      'riel',
      'wen',
      'thas',
      'lian',
      'sae',
      'vyn',
      'eth',
      'aya',
      'illa',
      'nara',
      'shae',
    ],
    surA: [
      'Silver',
      'Moon',
      'Star',
      'Dawn',
      'Leaf',
      'Sun',
      'Mist',
      'Willow',
      'Ever',
      'Dusk',
    ],
    surB: [
      'leaf',
      'song',
      'whisper',
      'glade',
      'bloom',
      'shade',
      'wind',
      'weaver',
      'bough',
      'chaser',
    ],
  ),
  NameCulture.drow: _p(
    start: [
      'Bel',
      'Dris',
      'Ilth',
      'Jhael',
      'Kel',
      'Mal',
      'Nym',
      'Quar',
      'Rhyl',
      'Sszar',
      'Tal',
      'Vrae',
      'Xull',
      'Zar',
      'Ver',
      'Ssyl',
    ],
    middle: ['ae', 'or', 'zi', 'ra', 'yn', 'sha', 'il', 'va'],
    endM: ['gorn', 'dan', 'zar', 'reth', 'nyl', 'thas', 'kar', 'vrin', 'zzt'],
    endF: [
      'iira',
      'ryn',
      'ssae',
      'nyth',
      'zyre',
      'lith',
      'ara',
      'venne',
      'shara',
    ],
    surA: [
      'Dark',
      'Night',
      'Web',
      'Spider',
      'Shadow',
      'Poison',
      'Grave',
      'Silk',
    ],
    surB: [
      'spinner',
      'shroud',
      'fang',
      'thorn',
      'bane',
      'creep',
      'veil',
      'whisper',
    ],
  ),
  NameCulture.dwarf: _p(
    start: [
      'Bal',
      'Bro',
      'Dur',
      'Gim',
      'Gro',
      'Hjal',
      'Kaz',
      'Mor',
      'Nor',
      'Orm',
      'Thra',
      'Thor',
      'Val',
      'Grim',
      'Dram',
      'Kil',
      'Bar',
      'Rurik',
    ],
    middle: ['a', 'u', 'o', 'ur', 'ar', 'in', 'un', 'or', 'ek'],
    endM: [
      'din',
      'grim',
      'nar',
      'rok',
      'bur',
      'dur',
      'mund',
      'gar',
      'thar',
      'brek',
      'lok',
      'nim',
    ],
    endF: [
      'hild',
      'dis',
      'ra',
      'lin',
      'na',
      'runa',
      'vora',
      'gunn',
      'bera',
      'stra',
    ],
    surA: [
      'Iron',
      'Stone',
      'Gold',
      'Deep',
      'Anvil',
      'Coal',
      'Battle',
      'Steel',
      'Ember',
      'Copper',
      'Rune',
      'Granite',
    ],
    surB: [
      'forge',
      'beard',
      'hammer',
      'delver',
      'fist',
      'shield',
      'breaker',
      'helm',
      'vein',
      'mantle',
      'brow',
      'grip',
    ],
  ),
  NameCulture.halfling: _p(
    start: [
      'Bil',
      'Cor',
      'Dro',
      'Fen',
      'Gil',
      'Hob',
      'Lin',
      'Mer',
      'Nib',
      'Per',
      'Rose',
      'Sam',
      'Tib',
      'Wil',
      'Pip',
      'Ando',
      'Marl',
      'Tuck',
    ],
    middle: ['ly', 'be', 'do', 'ri', 'wa', 'to', 'fi', 'ma', 'pe'],
    endM: ['bo', 'kin', 'wise', 'buck', 'ric', 'gar', 'don', 'ver', 'mus'],
    endF: ['la', 'ny', 'sy', 'wen', 'bell', 'da', 'rose', 'mina', 'lyn'],
    surA: [
      'Good',
      'Green',
      'Apple',
      'Butter',
      'Honey',
      'Hill',
      'Barrel',
      'Warm',
      'Merry',
      'Under',
    ],
    surB: [
      'foot',
      'barrel',
      'bottom',
      'hollow',
      'brook',
      'kettle',
      'basket',
      'hearth',
      'meadow',
      'top',
    ],
  ),
  NameCulture.gnome: _p(
    start: [
      'Bim',
      'Cog',
      'Dim',
      'Fiz',
      'Gim',
      'Jeb',
      'Kip',
      'Nim',
      'Ork',
      'Piz',
      'Quil',
      'Sniv',
      'Tik',
      'Wob',
      'Zan',
      'Bree',
      'Fen',
    ],
    middle: ['ble', 'wid', 'zle', 'no', 'ker', 'ta', 'gi', 'po'],
    endM: ['nock', 'wick', 'ble', 'gen', 'zap', 'bur', 'lin', 'fizz', 'top'],
    endF: ['ella', 'ippa', 'wyn', 'nix', 'ette', 'ory', 'ika', 'belle'],
    surA: [
      'Cog',
      'Spark',
      'Tinker',
      'Gear',
      'Quill',
      'Bumble',
      'Whistle',
      'Fizzle',
      'Copper',
      'Widget',
    ],
    surB: [
      'spring',
      'wrench',
      'bottom',
      'whistle',
      'button',
      'clank',
      'spanner',
      'gadget',
      'twist',
      'bang',
    ],
  ),
  NameCulture.orc: _p(
    start: [
      'Bak',
      'Dur',
      'Gash',
      'Gor',
      'Grak',
      'Kra',
      'Lug',
      'Mog',
      'Nar',
      'Rag',
      'Shak',
      'Thok',
      'Urz',
      'Zug',
      'Bru',
      'Hak',
      'Mur',
      'Vok',
    ],
    middle: ['a', 'u', 'o', 'ga', 'ur', 'ak', 'og', 'ru'],
    endM: [
      'nak',
      'gash',
      'rok',
      'dush',
      'mak',
      'zar',
      'thar',
      'grub',
      'luk',
      'skar',
      'tusk',
      'brak',
    ],
    endF: ['sha', 'ga', 'nka', 'ruk', 'zha', 'mora', 'kaa', 'ghra'],
    surA: [
      'Skull',
      'Blood',
      'Bone',
      'Iron',
      'War',
      'Ash',
      'Gore',
      'Black',
      'Red',
      'Death',
    ],
    surB: [
      'splitter',
      'render',
      'chewer',
      'maw',
      'howl',
      'crusher',
      'fang',
      'cleaver',
      'stomp',
      'drinker',
    ],
  ),
  NameCulture.goblin: _p(
    start: [
      'Bik',
      'Cru',
      'Fiz',
      'Gni',
      'Grib',
      'Hex',
      'Jib',
      'Klik',
      'Nib',
      'Riz',
      'Skri',
      'Snag',
      'Tik',
      'Vex',
      'Wug',
      'Yip',
      'Zib',
    ],
    middle: ['it', 'ga', 'nu', 'zi', 'ka', 'ob', 'ru'],
    endM: [
      'nix',
      'snik',
      'gob',
      'zap',
      'grit',
      'nak',
      'wik',
      'krunk',
      'zit',
      'brak',
      'tug',
    ],
    endF: [],
    surA: [
      'Rat',
      'Sock',
      'Rust',
      'Mud',
      'Bat',
      'Nail',
      'Sneak',
      'Fungus',
      'Pot',
      'Snot',
    ],
    surB: [
      'biter',
      'stealer',
      'nose',
      'toes',
      'poker',
      'licker',
      'runner',
      'kicker',
      'chewer',
      'finder',
    ],
  ),
  NameCulture.tiefling: _p(
    start: [
      'Az',
      'Bel',
      'Car',
      'Dam',
      'Eze',
      'Iro',
      'Kaa',
      'Lil',
      'Mep',
      'Nis',
      'Ori',
      'Ronn',
      'Sera',
      'Tha',
      'Vas',
      'Xar',
      'Zeh',
    ],
    middle: ['ri', 'mo', 'na', 'the', 'zi', 'ka', 'vel', 'sa'],
    endM: ['zar', 'thos', 'mon', 'reth', 'vek', 'gorn', 'us', 'axar', 'dris'],
    endF: ['ith', 'ara', 'ynne', 'issa', 'ael', 'orra', 'ysse', 'ime'],
    // Erdem adlari tieflinglerin klasik ikinci adidir; birlesik degil, tek kelime.
    surA: ['', '', '', ''],
    surB: [
      'Hope',
      'Sorrow',
      'Torment',
      'Reverence',
      'Ambition',
      'Glory',
      'Mercy',
      'Silence',
      'Fortune',
      'Chastity',
      'Doubt',
      'Zeal',
    ],
  ),
  NameCulture.dragonborn: _p(
    start: [
      'Arj',
      'Bal',
      'Dona',
      'Ghes',
      'Hesk',
      'Kri',
      'Med',
      'Nadar',
      'Pand',
      'Rhog',
      'Shamash',
      'Torin',
      'Uad',
      'Verth',
      'Zar',
    ],
    middle: ['ha', 'ka', 'ri', 'aa', 'ur', 'esh', 'an'],
    endM: ['ash', 'ar', 'esh', 'orn', 'axth', 'rash', 'thar', 'zar', 'ux'],
    endF: ['ann', 'ira', 'esa', 'wynn', 'ashi', 'ara', 'ixa'],
    surA: [
      'Clethtin',
      'Daar',
      'Fenkenka',
      'Kepesk',
      'Myastan',
      'Norixius',
      'Shestendel',
      'Turnuroth',
      'Verthisa',
    ],
    surB: [
      'vurin',
      'dorn',
      'brekk',
      'thull',
      'mairin',
      'zaal',
      'kaath',
      'moros',
    ],
  ),
  NameCulture.goliath: _p(
    start: [
      'Aukan',
      'Eglath',
      'Gae',
      'Ilik',
      'Kavaki',
      'Lo',
      'Maveith',
      'Nalla',
      'Orilo',
      'Pethani',
      'Thalai',
      'Uthal',
      'Vaunea',
    ],
    middle: ['a', 'i', 'ua', 'ka', 'ni', 'tha'],
    endM: ['nak', 'thal', 'gath', 'kan', 'mos', 'vahl', 'run'],
    endF: ['nea', 'lai', 'ani', 'ola', 'ura', 'ika'],
    surA: ['Stone', 'Sky', 'Peak', 'Cloud', 'Storm', 'Cliff', 'Snow', 'Frost'],
    surB: [
      'bearer',
      'hunter',
      'walker',
      'shoulder',
      'watcher',
      'seeker',
      'talker',
      'lifter',
    ],
  ),
  NameCulture.lizardfolk: _p(
    start: [
      'Ach',
      'Ba',
      'Dar',
      'Gar',
      'Hisk',
      'Ith',
      'Jash',
      'Kos',
      'Missh',
      'Ras',
      'Sar',
      'Ssur',
      'Thas',
      'Usk',
      'Xath',
      'Yiss',
    ],
    middle: ['ss', 'ka', 'ith', 'ru', 'sha', 'ax'],
    endM: ['ka', 'thik', 'sar', 'kesh', 'zul', 'rath', 'ssin', 'kroth', 'iss'],
    endF: [],
    surA: ['Swift', 'Silent', 'Deep', 'Green', 'Reed', 'Mud', 'Sun', 'Bog'],
    surB: [
      'claw',
      'tail',
      'fang',
      'scale',
      'tongue',
      'crest',
      'hunter',
      'basker',
    ],
  ),
  NameCulture.celestial: _p(
    start: [
      'Aur',
      'Cael',
      'Dae',
      'Ez',
      'Gab',
      'Ith',
      'Jeh',
      'Lum',
      'Mich',
      'Ori',
      'Rap',
      'Sar',
      'Ther',
      'Ura',
      'Zad',
      'Sol',
    ],
    middle: ['a', 'i', 'ri', 'the', 'na', 'lu', 'ma'],
    endM: ['iel', 'ael', 'thon', 'raph', 'dan', 'ariel', 'oth', 'mir'],
    endF: ['iel', 'aya', 'ithe', 'aris', 'elle', 'ora', 'ashe'],
    surA: [
      'Dawn',
      'Light',
      'Grace',
      'Sun',
      'Star',
      'Choir',
      'Silver',
      'Radiant',
    ],
    surB: [
      'bringer',
      'herald',
      'warden',
      'keeper',
      'singer',
      'bearer',
      'shield',
      'flame',
    ],
  ),
  NameCulture.undead: _p(
    start: [
      'Ash',
      'Cor',
      'Dro',
      'Grim',
      'Hol',
      'Kar',
      'Mor',
      'Nec',
      'Oss',
      'Pall',
      'Sep',
      'Thren',
      'Ur',
      'Vel',
      'Wrait',
      'Zeph',
    ],
    middle: ['a', 'e', 'ul', 'ro', 'ith', 'ar', 'os'],
    endM: ['ash', 'gul', 'mor', 'rith', 'thane', 'ux', 'vain', 'crypt', 'lich'],
    endF: ['essa', 'ira', 'wraith', 'ynne', 'aleth', 'ora'],
    surA: ['Pale', 'Hollow', 'Grave', 'Bone', 'Ash', 'Rot', 'Cold', 'Last'],
    surB: [
      'breath',
      'shroud',
      'lantern',
      'wake',
      'crown',
      'vigil',
      'echo',
      'hunger',
    ],
  ),
};

// --- Yer havuzlari (onek + ek) ----------------------------------------------

typedef _Compound = ({
  List<String> start,
  List<String> middle,
  List<String> end,
});

const Map<NameCulture, _Compound> _compounds = {
  NameCulture.place: (
    start: [
      'Aber',
      'Black',
      'Bright',
      'Cold',
      'Dun',
      'East',
      'Fal',
      'Green',
      'Grey',
      'High',
      'Iron',
      'Lang',
      'North',
      'Oak',
      'Red',
      'Stone',
      'Thorn',
      'West',
      'White',
      'Wind',
      'Bram',
      'Elder',
      'Fern',
      'Mill',
      'Ravens',
      'Swan',
      'Yew',
    ],
    middle: ['', '', 'er', 'en', 'in'],
    end: [
      'bridge',
      'brook',
      'burg',
      'dale',
      'fell',
      'ford',
      'gate',
      'haven',
      'hollow',
      'keep',
      'march',
      'mere',
      'moor',
      'reach',
      'shire',
      'stead',
      'watch',
      'wood',
      'thorpe',
      'combe',
      'cross',
      'barrow',
    ],
  ),
  NameCulture.city: (
    start: [
      'Ald',
      'Ambr',
      'Cor',
      'Dav',
      'Elm',
      'Gil',
      'Hal',
      'Kar',
      'Lum',
      'Mar',
      'Nev',
      'Ost',
      'Per',
      'Quen',
      'Sar',
      'Tal',
      'Val',
      'Ver',
      'Wyn',
      'Zan',
    ],
    middle: ['a', 'e', 'i', 'o', 'an', 'en', 'ar', 'or', 'is'],
    end: [
      'dris',
      'gard',
      'holm',
      'kar',
      'mor',
      'nis',
      'polis',
      'port',
      'spire',
      'tor',
      'vane',
      'wall',
      'gate',
      'crest',
      'haven',
      'reach',
    ],
  ),
  NameCulture.fortress: (
    start: [
      'Black',
      'Bone',
      'Dread',
      'Grim',
      'Iron',
      'Storm',
      'Stone',
      'Thorn',
      'War',
      'Wolf',
      'Dragon',
      'Ash',
      'Frost',
      'Raven',
      'High',
    ],
    middle: ['', '', 's', 'en'],
    end: [
      'hold',
      'keep',
      'watch',
      'gate',
      'spire',
      'guard',
      'bastion',
      'wall',
      'reach',
      'crag',
      'throne',
      'perch',
      'redoubt',
      'march',
    ],
  ),
  NameCulture.forest: (
    start: [
      'Dusk',
      'Elder',
      'Fern',
      'Gloom',
      'Green',
      'Mist',
      'Moss',
      'Oak',
      'Silver',
      'Tangle',
      'Thistle',
      'Whisper',
      'Wild',
      'Yew',
      'Amber',
    ],
    middle: ['', '', 'en', 'er'],
    end: [
      'wood',
      'wold',
      'thicket',
      'grove',
      'copse',
      'shaw',
      'briar',
      'holt',
      'weald',
      'bough',
      'hollow',
      'glade',
    ],
  ),
  NameCulture.mountain: (
    start: [
      'Cloud',
      'Storm',
      'Frost',
      'Grim',
      'Iron',
      'Sky',
      'Sun',
      'Wind',
      'Bone',
      'Ash',
      'Giants',
      'Kings',
      'Dragon',
      'Snow',
    ],
    middle: ['', '', 's'],
    end: [
      'peak',
      'horn',
      'crag',
      'spine',
      'tooth',
      'fang',
      'summit',
      'ridge',
      'pass',
      'scarp',
      'cairn',
      'throne',
      'shoulder',
      'mantle',
    ],
  ),
  NameCulture.water: (
    start: [
      'Silver',
      'Black',
      'Swift',
      'Slow',
      'Salt',
      'Cold',
      'Clear',
      'Serpent',
      'Amber',
      'Otter',
      'Grey',
      'Sable',
      'Mourn',
    ],
    middle: ['', '', 's', 'en'],
    end: [
      'run',
      'flow',
      'water',
      'mere',
      'tarn',
      'fen',
      'strand',
      'sound',
      'channel',
      'race',
      'bourne',
      'deep',
      'ford',
      'shallows',
    ],
  ),
  NameCulture.island: (
    start: [
      'Sea',
      'Storm',
      'Salt',
      'Gull',
      'Coral',
      'Fog',
      'Wreck',
      'Whale',
      'Ember',
      'Kraken',
      'Pearl',
      'Siren',
    ],
    middle: ['', '', 's', "'s "],
    end: [
      'isle',
      'holm',
      'skerry',
      'reef',
      'atoll',
      'rock',
      'cay',
      'strand',
      'spit',
      'shoal',
      'perch',
      'crown',
    ],
  ),
};

// --- Kalip havuzlari (iki kelime + sablon) ----------------------------------

/// [en]/[tr] sablonlarinda {a} ve {b} yerine kelimeler konur.
typedef _Phrase = ({
  List<String> aEn,
  List<String> bEn,
  List<String> aTr,
  List<String> bTr,
  String en,
  String tr,
});

const Map<NameCulture, _Phrase> _phrases = {
  // Tabaxi adlari betimleyici tamlamalardir; hece havuzu yerine kalip.
  NameCulture.tabaxi: (
    aEn: [
      'Cloud',
      'Jade',
      'Whisper',
      'Swift Paw',
      'Quiet Step',
      'Moon',
      'Dust',
      'Amber Eye',
      'Night',
      'Copper Tail',
      'Wind',
      'Bright Claw',
    ],
    bEn: [
      'Water',
      'Mountain',
      'Rain',
      'Dawn',
      'Long Hunt',
      'Shadow',
      'Tall Grass',
      'Storm',
      'Standing Stone',
      'First Fire',
    ],
    aTr: [
      'Cloud',
      'Jade',
      'Whisper',
      'Swift Paw',
      'Quiet Step',
      'Moon',
      'Dust',
      'Amber Eye',
      'Night',
      'Copper Tail',
      'Wind',
      'Bright Claw',
    ],
    bTr: [
      'Water',
      'Mountain',
      'Rain',
      'Dawn',
      'Long Hunt',
      'Shadow',
      'Tall Grass',
      'Storm',
      'Standing Stone',
      'First Fire',
    ],
    en: '{a} on the {b}',
    tr: '{a} on the {b}',
  ),
  NameCulture.ruin: (
    aEn: [
      'Broken',
      'Sunken',
      'Lost',
      'Cinder',
      'Hollow',
      'Weeping',
      'Silent',
      'Bleak',
      'Shattered',
      'Drowned',
      'Buried',
      'Fallen',
    ],
    bEn: [
      'Halls',
      'Vaults',
      'Spire',
      'Barrows',
      'Cloister',
      'Foundry',
      'Sepulchre',
      'Arch',
      'Cistern',
      'Ossuary',
      'Terrace',
      'Menagerie',
    ],
    aTr: [
      'Kırık',
      'Batık',
      'Kayıp',
      'Kor',
      'Boş',
      'Ağlayan',
      'Sessiz',
      'Kasvetli',
      'Paramparça',
      'Boğulmuş',
      'Gömülü',
      'Düşmüş',
    ],
    bTr: [
      'Salonlar',
      'Mahzenler',
      'Kule',
      'Höyükler',
      'Manastır',
      'Dökümhane',
      'Türbe',
      'Kemer',
      'Sarnıç',
      'Kemiklik',
      'Teras',
      'Hayvanat',
    ],
    en: 'The {a} {b}',
    tr: '{a} {b}',
  ),
  NameCulture.region: (
    aEn: [
      'Ashen',
      'Sunless',
      'Broken',
      'Frozen',
      'Whispering',
      'Sundered',
      'Endless',
      'Emerald',
      'Bitter',
      'Golden',
      'Forgotten',
      'Screaming',
      'Silent',
      'Blighted',
      'Weeping',
    ],
    bEn: [
      'Reach',
      'Marches',
      'Wastes',
      'Expanse',
      'Downs',
      'Barrens',
      'Hinterlands',
      'Vale',
      'Steppes',
      'Frontier',
      'Verge',
      'Fens',
      'Highlands',
      'Basin',
    ],
    aTr: [
      'Küllü',
      'Güneşsiz',
      'Kırık',
      'Donmuş',
      'Fısıldayan',
      'Yarık',
      'Sonsuz',
      'Zümrüt',
      'Acı',
      'Altın',
      'Unutulmuş',
      'Çığlıklı',
      'Sessiz',
      'Kurumuş',
      'Ağlayan',
    ],
    bTr: [
      'Diyar',
      'Uçbeyliği',
      'Çorak',
      'Yayla',
      'Bozkır',
      'Kıraç',
      'Hudut',
      'Vadi',
      'Ova',
      'Sınır',
      'Eşik',
      'Bataklık',
      'Yüksekler',
      'Havza',
    ],
    en: 'The {a} {b}',
    tr: '{a} {b}',
  ),
  NameCulture.tavern: (
    aEn: [
      'Golden',
      'Rusty',
      'Laughing',
      'Silver',
      'Broken',
      'Sleeping',
      'Prancing',
      'Drunken',
      'Wandering',
      'Crimson',
      'Salty',
      'Weary',
      'Hidden',
      'Roaring',
      'Gilded',
      'Crooked',
      'Dancing',
      'Silent',
      'Blind',
      'Thirsty',
      'Fat',
      'Wicked',
      'Lucky',
      'Grinning',
    ],
    bEn: [
      'Dragon',
      'Griffon',
      'Tankard',
      'Boar',
      'Anchor',
      'Crown',
      'Lantern',
      'Stag',
      'Mermaid',
      'Raven',
      'Barrel',
      'Sword',
      'Rose',
      'Hound',
      'Kettle',
      'Wolf',
      'Compass',
      'Goat',
      'Pony',
      'Cauldron',
      'Fiddle',
      'Bell',
      'Gauntlet',
      'Otter',
    ],
    aTr: [
      'Altın',
      'Paslı',
      'Gülen',
      'Gümüş',
      'Kırık',
      'Uyuyan',
      'Şahlanan',
      'Sarhoş',
      'Gezgin',
      'Kızıl',
      'Tuzlu',
      'Yorgun',
      'Gizli',
      'Kükreyen',
      'Yaldızlı',
      'Eğri',
      'Dans Eden',
      'Sessiz',
      'Kör',
      'Susamış',
      'Şişko',
      'Kötücül',
      'Şanslı',
      'Sırıtan',
    ],
    bTr: [
      'Ejderha',
      'Grifon',
      'Maşrapa',
      'Yaban Domuzu',
      'Çapa',
      'Taç',
      'Fener',
      'Geyik',
      'Denizkızı',
      'Kuzgun',
      'Fıçı',
      'Kılıç',
      'Gül',
      'Tazı',
      'Güğüm',
      'Kurt',
      'Pusula',
      'Keçi',
      'Midilli',
      'Kazan',
      'Keman',
      'Çan',
      'Zırhlı Eldiven',
      'Su Samuru',
    ],
    en: 'The {a} {b}',
    tr: '{a} {b}',
  ),
  NameCulture.shop: (
    aEn: [
      'Gilded',
      'Copper',
      'Whetted',
      'Threaded',
      'Bubbling',
      'Dusty',
      'Honest',
      'Clever',
      'Singing',
      'Patient',
      'Green',
      'Amber',
      'Second',
      'Fine',
      'Brass',
      'Curious',
    ],
    bEn: [
      'Anvil',
      'Needle',
      'Retort',
      'Ledger',
      'Quill',
      'Mortar',
      'Awl',
      'Sickle',
      'Loom',
      'Crucible',
      'Scale',
      'Wheel',
      'Lantern',
      'Coffer',
      'Spindle',
      'Chisel',
    ],
    aTr: [
      'Yaldızlı',
      'Bakır',
      'Bilenmiş',
      'İplikli',
      'Fokurdayan',
      'Tozlu',
      'Dürüst',
      'Kurnaz',
      'Şarkı Söyleyen',
      'Sabırlı',
      'Yeşil',
      'Kehribar',
      'İkinci',
      'İnce',
      'Pirinç',
      'Meraklı',
    ],
    bTr: [
      'Örs',
      'İğne',
      'İmbik',
      'Defter',
      'Tüy Kalem',
      'Havan',
      'Biz',
      'Orak',
      'Dokuma Tezgâhı',
      'Pota',
      'Terazi',
      'Çark',
      'Fener',
      'Kasa',
      'İğ',
      'Keski',
    ],
    en: 'The {a} {b}',
    tr: '{a} {b}',
  ),
  NameCulture.temple: (
    aEn: [
      'Silent',
      'Everburning',
      'First',
      'Weeping',
      'Radiant',
      'Sunken',
      'Ninefold',
      'Quiet',
      'Hallowed',
      'Broken',
      'Ivory',
      'Dawnlit',
    ],
    bEn: [
      'Flame',
      'Dawn',
      'Covenant',
      'Vigil',
      'Chalice',
      'Bell',
      'Wheel',
      'Star',
      'Reliquary',
      'Ash',
      'Fountain',
      'Oath',
    ],
    aTr: [
      'Sessiz',
      'Sönmeyen',
      'İlk',
      'Ağlayan',
      'Işıyan',
      'Batık',
      'Dokuz Katlı',
      'Sakin',
      'Kutsanmış',
      'Kırık',
      'Fildişi',
      'Şafak',
    ],
    bTr: [
      'Alev',
      'Şafak',
      'Ahit',
      'Nöbet',
      'Kadeh',
      'Çan',
      'Çark',
      'Yıldız',
      'Emanet',
      'Kül',
      'Çeşme',
      'Yemin',
    ],
    en: 'Temple of the {a} {b}',
    tr: '{a} {b} Tapınağı',
  ),
  NameCulture.guild: (
    aEn: [
      'Silver',
      'Iron',
      'Quiet',
      'Honest',
      'Open',
      'Sable',
      'Gilded',
      'Steady',
      'Long',
      'Amber',
      'Grey',
      'Deft',
    ],
    bEn: [
      'Hand',
      'Ledger',
      'Key',
      'Wheel',
      'Chain',
      'Hammer',
      'Scale',
      'Compass',
      'Knot',
      'Bench',
      'Seal',
      'Thread',
    ],
    aTr: [
      'Gümüş',
      'Demir',
      'Sessiz',
      'Dürüst',
      'Açık',
      'Kara',
      'Yaldızlı',
      'Sağlam',
      'Uzun',
      'Kehribar',
      'Gri',
      'Becerikli',
    ],
    bTr: [
      'El',
      'Defter',
      'Anahtar',
      'Çark',
      'Zincir',
      'Çekiç',
      'Terazi',
      'Pusula',
      'Düğüm',
      'Tezgâh',
      'Mühür',
      'İplik',
    ],
    en: 'The Guild of the {a} {b}',
    tr: '{a} {b} Loncası',
  ),
  NameCulture.nobleHouse: (
    aEn: [
      'Ravens',
      'Thorn',
      'Ash',
      'Vane',
      'Mor',
      'Cael',
      'Dray',
      'Ser',
      'Val',
      'Wyn',
      'Ost',
      'Bran',
      'Lyr',
      'Karth',
    ],
    bEn: [
      'court',
      'mere',
      'wold',
      'strand',
      'gate',
      'holm',
      'vale',
      'ford',
      'crest',
      'march',
      'hall',
      'row',
      'stone',
      'brook',
    ],
    aTr: [
      'Ravens',
      'Thorn',
      'Ash',
      'Vane',
      'Mor',
      'Cael',
      'Dray',
      'Ser',
      'Val',
      'Wyn',
      'Ost',
      'Bran',
      'Lyr',
      'Karth',
    ],
    bTr: [
      'court',
      'mere',
      'wold',
      'strand',
      'gate',
      'holm',
      'vale',
      'ford',
      'crest',
      'march',
      'hall',
      'row',
      'stone',
      'brook',
    ],
    en: 'House {a}{b}',
    tr: '{a}{b} Hanedanı',
  ),
  NameCulture.mercenary: (
    aEn: [
      'Iron',
      'Red',
      'Black',
      'Broken',
      'Grim',
      'Ninth',
      'Silent',
      'Bloody',
      'Wandering',
      'Cold',
      'Last',
      'Bitter',
    ],
    bEn: [
      'Wolves',
      'Lances',
      'Banners',
      'Blades',
      'Ravens',
      'Spears',
      'Hounds',
      'Shields',
      'Wardens',
      'Company',
      'Riders',
      'Boars',
    ],
    aTr: [
      'Demir',
      'Kızıl',
      'Kara',
      'Kırık',
      'Acımasız',
      'Dokuzuncu',
      'Sessiz',
      'Kanlı',
      'Gezgin',
      'Soğuk',
      'Son',
      'Acı',
    ],
    bTr: [
      'Kurtlar',
      'Mızraklar',
      'Sancaklar',
      'Kılıçlar',
      'Kuzgunlar',
      'Süngüler',
      'Tazılar',
      'Kalkanlar',
      'Muhafızlar',
      'Bölük',
      'Süvariler',
      'Domuzlar',
    ],
    en: 'The {a} {b}',
    tr: '{a} {b}',
  ),
  NameCulture.cult: (
    aEn: [
      'Hollow',
      'Crimson',
      'Whispering',
      'Unblinking',
      'Drowned',
      'Wormwood',
      'Ninefold',
      'Faceless',
      'Starving',
      'Patient',
    ],
    bEn: [
      'Eye',
      'Mouth',
      'Crown',
      'Choir',
      'Hunger',
      'Lantern',
      'Thorn',
      'Womb',
      'Mirror',
      'Tide',
    ],
    aTr: [
      'Boş',
      'Kızıl',
      'Fısıldayan',
      'Kırpmayan',
      'Boğulmuş',
      'Pelin',
      'Dokuz Katlı',
      'Yüzsüz',
      'Aç',
      'Sabırlı',
    ],
    bTr: [
      'Göz',
      'Ağız',
      'Taç',
      'Koro',
      'Açlık',
      'Fener',
      'Diken',
      'Rahim',
      'Ayna',
      'Gelgit',
    ],
    en: 'Cult of the {a} {b}',
    tr: '{a} {b} Tarikatı',
  ),
  NameCulture.ship: (
    aEn: [
      'Sea',
      'Storm',
      'Salt',
      'Dawn',
      'Wave',
      'Star',
      'Wind',
      'Tide',
      'Moon',
      'Gull',
      'Fog',
      'Kraken',
    ],
    bEn: [
      'wraith',
      'chaser',
      'dancer',
      'breaker',
      'runner',
      'song',
      'wing',
      'maiden',
      'reaver',
      'harrow',
      'crest',
      'widow',
    ],
    aTr: [
      'Deniz',
      'Fırtına',
      'Tuz',
      'Şafak',
      'Dalga',
      'Yıldız',
      'Rüzgâr',
      'Gelgit',
      'Ay',
      'Martı',
      'Sis',
      'Kraken',
    ],
    bTr: [
      'Hayaleti',
      'Avcısı',
      'Dansçısı',
      'Kıranı',
      'Koşucusu',
      'Şarkısı',
      'Kanadı',
      'Kızı',
      'Yağmacısı',
      'Tırmığı',
      'Tepesi',
      'Dulu',
    ],
    en: 'The {a}{b}',
    tr: '{a} {b}',
  ),
  NameCulture.magicItem: (
    aEn: [
      'Blade',
      'Circlet',
      'Cloak',
      'Ring',
      'Staff',
      'Chime',
      'Lantern',
      'Mask',
      'Gauntlet',
      'Horn',
      'Mirror',
      'Key',
      'Bell',
      'Locket',
    ],
    bEn: [
      'Whispers',
      'Nine Winters',
      'the Drowned King',
      'Quiet Hours',
      'Borrowed Time',
      'the Last Dawn',
      'Seven Doors',
      'Waking Ash',
      'the Hollow Star',
      'Unspoken Names',
      'the Patient Tide',
      'Cinders',
      'the Grey Vow',
      'Second Sight',
    ],
    aTr: [
      'Kılıcı',
      'Tacı',
      'Pelerini',
      'Yüzüğü',
      'Asası',
      'Çanı',
      'Feneri',
      'Maskesi',
      'Eldiveni',
      'Borusu',
      'Aynası',
      'Anahtarı',
      'Çıngırağı',
      'Madalyonu',
    ],
    bTr: [
      'Fısıltılar',
      'Dokuz Kış',
      'Boğulmuş Kral',
      'Sessiz Saatler',
      'Ödünç Zaman',
      'Son Şafak',
      'Yedi Kapı',
      'Uyanan Kül',
      'Boş Yıldız',
      'Söylenmeyen Adlar',
      'Sabırlı Gelgit',
      'Korlar',
      'Gri Yemin',
      'İkinci Görüş',
    ],
    en: '{a} of {b}',
    tr: '{b} {a}',
  ),
  NameCulture.tome: (
    aEn: [
      'Codex',
      'Testament',
      'Ledger',
      'Chronicle',
      'Catechism',
      'Atlas',
      'Almanac',
      'Bestiary',
      'Litany',
      'Treatise',
      'Cantos',
      'Register',
    ],
    bEn: [
      'Drowned Saints',
      'Broken Years',
      'Small Gods',
      'Hollow Kings',
      'Bitter Salt',
      'the Third Moon',
      'Quiet Fire',
      'Nameless Roads',
      'Falling Towers',
      'Sleeping Beasts',
      'the Ninth Hour',
      'Unfinished Work',
    ],
    aTr: [
      'Kodeksi',
      'Ahdi',
      'Defteri',
      'Vakayinamesi',
      'İlmihali',
      'Atlası',
      'Almanağı',
      'Bestiyeri',
      'Duası',
      'Risalesi',
      'Kantosu',
      'Sicili',
    ],
    bTr: [
      'Boğulmuş Azizler',
      'Kırık Yıllar',
      'Küçük Tanrılar',
      'Boş Krallar',
      'Acı Tuz',
      'Üçüncü Ay',
      'Sessiz Ateş',
      'Adsız Yollar',
      'Düşen Kuleler',
      'Uyuyan Canavarlar',
      'Dokuzuncu Saat',
      'Bitmemiş Eser',
    ],
    en: 'The {a} of the {b}',
    tr: '{b} {a}',
  ),
  NameCulture.festival: (
    aEn: [
      'Feast',
      'Night',
      'Vigil',
      'Procession',
      'Rite',
      'Fair',
      'Fast',
      'Masque',
      'Burning',
      'Blessing',
    ],
    bEn: [
      'Lanterns',
      'Salt',
      'Ash',
      'the Long Dark',
      'First Frost',
      'Nine Bells',
      'the Quiet Dead',
      'Green Sap',
      'Returning Ships',
      'Broken Bread',
    ],
    aTr: [
      'Şöleni',
      'Gecesi',
      'Nöbeti',
      'Alayı',
      'Ayini',
      'Panayırı',
      'Orucu',
      'Balosu',
      'Yakma Töreni',
      'Kutsaması',
    ],
    bTr: [
      'Fenerler',
      'Tuz',
      'Kül',
      'Uzun Karanlık',
      'İlk Ayaz',
      'Dokuz Çan',
      'Sessiz Ölüler',
      'Yeşil Öz',
      'Dönen Gemiler',
      'Bölünmüş Ekmek',
    ],
    en: 'The {a} of {b}',
    tr: '{b} {a}',
  ),
  NameCulture.epithet: (
    aEn: [
      'the Pale',
      'the Kindly',
      'the Unbowed',
      'the Twice-Drowned',
      'the Quiet',
      'the Gilded',
      'the Oathless',
      'the Patient',
      'the Hollow',
      'the Wandering',
      'the Bitter',
      'the Undying',
      'the Merciful',
      'the Crooked',
    ],
    bEn: [
      'of the Ashen Road',
      'of Nine Winters',
      'of the Broken Gate',
      'of the Last Ship',
      'of the Silent Choir',
      'of the Salt Marches',
      'of the Long Hunt',
      'of the Sunken Vault',
      'of the Grey Vow',
      'of the Whispering Fen',
    ],
    aTr: [
      'Solgun',
      'Merhametli',
      'Boyun Eğmez',
      'İki Kez Boğulan',
      'Sessiz',
      'Yaldızlı',
      'Yeminsiz',
      'Sabırlı',
      'Boş',
      'Gezgin',
      'Acı',
      'Ölümsüz',
      'Bağışlayan',
      'Eğri',
    ],
    // Turkcede lakap "Solgun, Küllü Yol'dan" kalibiyla dogal duruyor; bu
    // yuzden ikinci parca dogrudan ayrilma halinde yaziliyor.
    bTr: [
      'Küllü Yol\'dan',
      'Dokuz Kış\'tan',
      'Kırık Kapı\'dan',
      'Son Gemi\'den',
      'Sessiz Koro\'dan',
      'Tuzlu Uçlar\'dan',
      'Uzun Av\'dan',
      'Batık Mahzen\'den',
      'Gri Yemin\'den',
      'Fısıldayan Bataklık\'tan',
    ],
    en: '{a}, {b}',
    tr: '{a}, {b}',
  ),
};

/// [count] adet isim uretir.
///
/// [turkish] kalip adlari (meyhane/lonca/tapinak/eser...) Turkce uretir; kisi
/// ve yer adlari fantastik kokenlidir, cevrilmez. [gender] yalnizca kisi
/// kulturlerinde ve [NameCultureInfo.hasGender] dogruysa etkilidir.
/// [surname] kisi adlarina soyad/lakap ekler. [rng] verilirse sonuc
/// deterministiktir.
List<String> generateNames(
  NameCulture culture, {
  int count = 10,
  bool turkish = false,
  NameGender gender = NameGender.any,
  bool surname = false,
  Random? rng,
}) {
  final random = rng ?? Random();
  final n = count < 1 ? 1 : count;

  // Tekrar etmesin diye kume; cok denemeden sonra biten havuzda takilmamak
  // icin deneme siniri var.
  final out = <String>{};
  for (var attempt = 0; attempt < n * 20 && out.length < n; attempt++) {
    out.add(
      generateName(
        culture,
        turkish: turkish,
        gender: gender,
        surname: surname,
        rng: random,
      ),
    );
  }
  return out.toList();
}

/// Tek bir isim uretir (bkz. [generateNames]).
String generateName(
  NameCulture culture, {
  bool turkish = false,
  NameGender gender = NameGender.any,
  bool surname = false,
  Random? rng,
}) {
  final random = rng ?? Random();

  final phrase = _phrases[culture];
  if (phrase != null) return _fromPhrase(phrase, random, turkish);

  final compound = _compounds[culture];
  if (compound != null) return _fromCompound(compound, random);

  final person = _persons[culture]!;
  final given = _fromPerson(person, random, gender);
  if (!surname || person.surB.isEmpty) return given;
  return '$given ${_surnameOf(person, random)}';
}

String _pick(List<String> list, Random rng) => list[rng.nextInt(list.length)];

String _fromPhrase(_Phrase phrase, Random rng, bool turkish) {
  final a = _pick(turkish ? phrase.aTr : phrase.aEn, rng);
  final b = _pick(turkish ? phrase.bTr : phrase.bEn, rng);
  return (turkish ? phrase.tr : phrase.en)
      .replaceAll('{a}', a)
      .replaceAll('{b}', b);
}

String _fromCompound(_Compound pool, Random rng) {
  final start = _pick(pool.start, rng);
  final end = _pick(pool.end, rng);
  final middle = rng.nextBool() ? _pick(pool.middle, rng) : '';
  return '$start$middle$end';
}

String _fromPerson(_Person pool, Random rng, NameGender gender) {
  final start = _pick(pool.start, rng);
  final end = switch (gender) {
    NameGender.male => _pick(pool.endM, rng),
    NameGender.female => _pick(pool.endF.isEmpty ? pool.endM : pool.endF, rng),
    NameGender.any => _pick(
      pool.endF.isEmpty ? pool.endM : [...pool.endM, ...pool.endF],
      rng,
    ),
  };
  // Orta hece %50 ihtimalle; hep eklenirse isimler tekduze uzuyor.
  final middle = rng.nextBool() ? _pick(pool.middle, rng) : '';
  return '$start$middle$end';
}

String _surnameOf(_Person pool, Random rng) {
  final a = pool.surA.isEmpty ? '' : _pick(pool.surA, rng);
  var b = _pick(pool.surB, rng);
  // "Barrelbarrel" gibi kendini tekrar eden soyadlari ele; birkac deneme
  // yeter, havuzlar kucuk oldugu icin sonsuz donguye girmemeli.
  for (var i = 0; i < 5 && a.toLowerCase() == b.toLowerCase(); i++) {
    b = _pick(pool.surB, rng);
  }
  final joined = a.isEmpty ? b : '$a${pool.surJoin}$b';
  return '${pool.surPrefix}$joined';
}
